Repository mitodl/ocw-studio, pull requests merged in 2021-12, with the labels that each got.

#840 Populate additional fields when publishing via mass_publish
  content_sync/api.py
  content_sync/api_test.py
  websites/views_test.py
Labels: Needs Review

#832 Use task decorator to prevent multiple instances of recurring scheduled tasks
  content_sync/decorators.py
  content_sync/decorators_test.py
  content_sync/tasks.py
  gdrive_sync/tasks.py
  videos/tasks.py
Labels: Needs Review

#843 Remove obsolete pages and content during OCW import
  ocw_import/api.py
  ocw_import/api_test.py
Labels: Needs Review

#844 Do not show menu dropdown for global admins or site owner
  static/js/components/SiteCollaboratorList.test.tsx
  static/js/components/StudioList.tsx
Labels: Needs Review

#849 refactor fix for deleting orphaned git files
  content_sync/backends/base.py
  content_sync/backends/base_test.py
  content_sync/backends/github.py
  content_sync/backends/github_test.py
  content_sync/management/commands/sync_website_to_backend.py
  content_sync/tasks.py
  content_sync/tasks_test.py
Labels: Needs Review

#860 Add all metadata keys w/blank values for imported google drive content
  gdrive_sync/api.py
  gdrive_sync/api_test.py
  videos/tasks_test.py
  websites/config_schema/api_test.py
  websites/conftest.py
  websites/management/commands/update_content_metadata.py
  websites/site_config_api.py
  websites/site_config_api_test.py
Labels: Needs Review

#857 add site search
  static/js/hooks/effect.ts
  static/js/hooks/state.ts
  static/js/pages/SitesDashboard.test.tsx
  static/js/pages/SitesDashboard.tsx
  static/js/query-configs/websites.ts
  static/scss/dashboard.scss
Labels: Waiting on Author

#852 Concourse in a docker container
  README.md
  docker-compose.yml
Labels: Needs Review

#855 Prevent users from creating content with forbidden filenames
  gdrive_sync/api.py
  gdrive_sync/api_test.py
  websites/constants.py
  websites/utils.py
  websites/views.py
  websites/views_test.py
Labels: Waiting on Author

#858 Fix outdated starter configs, add instruction to update them in README
  README.md
  localdev/configs/basic-site-config.yml
  localdev/configs/default-course-config.yml
  localdev/management/commands/override_site_config.py
  localdev/starters/example-starter/ocw-studio.yml
  static/js/resources/basic-course-config.json
  static/js/resources/default-course-config.json
Labels: Waiting on Author

#865 remove an unused JS dependency
  package.json
  yarn.lock
Labels: Waiting on Author

#850 Make youtube videos public for live publishing
  content_sync/api.py
  content_sync/api_test.py
  videos/tasks.py
  videos/youtube.py
  videos/youtube_test.py
Labels: Waiting on Author

#854 Log an error when a pipeline fails
  websites/api.py
  websites/api_test.py
Labels: Waiting on Author

#851 Run incomplete_publish_build_statuses task only if a pipeline backend is set
  content_sync/tasks.py
  content_sync/tasks_test.py
Labels: Waiting on Author

#869 split reordering UI off from RelationWidget into SortableSelect component
  static/js/components/widgets/RelationField.test.tsx
  static/js/components/widgets/RelationField.tsx
  static/js/components/widgets/SortableSelect.test.tsx
  static/js/components/widgets/SortableSelect.tsx
  static/js/util/integration_test_helper.tsx
Labels: Waiting on Author

#875 Fix Youtube API status update call
  videos/youtube.py
  videos/youtube_test.py
Labels: Waiting on Author

#873 Fix task bug caused by decorator
  content_sync/tasks.py
  content_sync/tasks_test.py
Labels: Waiting on Author

#877 Adjust query in content_sync.tasks.check_incomplete_publish_build_statuses
  content_sync/tasks.py
  content_sync/tasks_test.py
Labels: Needs Review, Waiting on Author

#874 add uids to metadata output
  content_sync/serializers.py
  content_sync/serializers_test.py
  localdev/configs/ocw-course-site-config.yml
  ocw_import/api.py
  ocw_import/api_test.py
  static/js/resources/ocw-course-site-config.json
  test_ocw2hugo/1-050-engineering-mechanics-i-fall-2007/data/course.json
  test_ocw2hugo/1-050-engineering-mechanics-i-fall-2007/data/course_legacy.json
  test_ocw2hugo/1-201j-transportation-systems-analysis-demand-and-economics-fall-2008/data/course.json
  test_ocw2hugo/1-201j-transportation-systems-analysis-demand-and-economics-fall-2008/data/course_legacy.json
  test_ocw2hugo/biology/data/course.json
  test_ocw2hugo/biology/data/course_legacy.json
  test_ocw2hugo/es-s41-speak-italian-with-your-mouth-full-spring-2012/data/course.json
  test_ocw2hugo/es-s41-speak-italian-with-your-mouth-full-spring-2012/data/course_legacy.json
Labels: Needs Review

#867 Descriptive message on front end for publishing warnings
  static/js/components/PublishDrawer.test.tsx
  static/js/components/PublishDrawer.tsx
  static/js/types/websites.ts
  static/js/util/factories/websites.ts
  websites/api.py
  websites/api_test.py
  websites/serializers.py
  websites/serializers_test.py
  websites/views.py
  websites/views_test.py
Labels: Waiting on Author

#864 Retry all pipeline steps up to 3x
  content_sync/pipelines/definitions/concourse/site-pipeline.yml
Labels: Needs Review

#881 Use static version file as trigger for sites other than ocw-www
  content_sync/pipelines/concourse.py
  content_sync/pipelines/definitions/concourse/site-pipeline.yml
Labels: Needs Review

#883 Revert "use static version file as trigger for sites other than ocw-www"
  content_sync/pipelines/concourse.py
  content_sync/pipelines/definitions/concourse/site-pipeline.yml
Labels: Needs Review
