Repository mitodl/ocw-studio, pull requests merged in 2021-04, with the labels that each got.

#168 add Boolean widget
  localdev/starters/site-config-override.yml
  static/js/components/SiteAddContent.test.tsx
  static/js/components/SiteContentListing.test.tsx
  static/js/components/SiteEditContent.test.tsx
  static/js/components/forms/SiteAddContentForm.test.tsx
  static/js/components/forms/SiteAddContentForm.tsx
  static/js/components/forms/SiteContentField.test.tsx
  static/js/components/forms/SiteContentField.tsx
  static/js/components/forms/validation.test.ts
  static/js/components/widgets/BooleanField.test.tsx
  static/js/components/widgets/BooleanField.tsx
  static/js/components/widgets/FileUploadField.tsx
  static/js/components/widgets/MarkdownEditor.tsx
  static/js/constants.ts
  static/js/lib/site_content.test.ts
  static/js/lib/site_content.ts
  static/js/pages/MarkdownEditorTestPage.tsx
  static/js/types/websites.ts
  static/js/util/factories/websites.ts
  websites/config_schema/site-config-schema.yml
Labels: Waiting on Author

#169 Fix file upload
  static/js/components/forms/validation.test.ts
  static/js/components/forms/validation.ts
Labels: Waiting on Author

#165 Integrate Touchstone login
  .env.example
  .github/workflows/ci.yml
  README.md
  app.json
  apt.txt
  main/settings.py
  main/settings_test.py
  main/urls.py
  main/views.py
  main/views_test.py
  requirements.in
  requirements.txt
  static/js/components/Header.test.tsx
  static/js/components/Header.tsx
  static/js/components/SiteCollaboratorEditPanel.test.tsx
  static/js/components/SiteCollaboratorEditPanel.tsx
  static/js/components/SiteCollaboratorList.test.tsx
  static/js/components/SiteCollaboratorList.tsx
  static/js/lib/urls.test.ts
  static/js/lib/urls.ts
  static/js/pages/App.test.tsx
  static/js/pages/App.tsx
  static/js/pages/HomePage.test.tsx
  static/js/pages/HomePage.tsx
  static/js/pages/SitePage.tsx
  static/js/query-configs/websites.ts
  static/js/test_setup.ts
  static/js/types/globals.d.ts
  static/js/types/websites.ts
  static/js/util/factories/websites.ts
  static/scss/button.scss
  static/scss/home-page.scss
  static/scss/layout.scss
  users/admin.py
  users/factories.py
  users/migrations/0002_users_active_default.py
  users/models.py
  websites/serializers.py
  websites/serializers_test.py
  websites/views.py
  websites/views_test.py
Labels: Waiting on Author

#174 Content -> Body
  localdev/starters/site-config-override.yml
  static/js/components/SiteAddContent.test.tsx
  static/js/components/forms/SiteAddContentForm.test.tsx
  static/js/constants.ts
  static/js/lib/site_content.test.ts
  static/js/util/factories/websites.ts
  websites/config_schema/resources/valid-config.yml
Labels: Waiting on Author

#188 Add settings for using X-Forwarded-* headers
  app.json
  main/settings.py
Labels: Waiting on Author

#173 Collaborator add/edit modal drawer
  static/js/components/SiteCollaboratorAddPanel.test.tsx
  static/js/components/SiteCollaboratorAddPanel.tsx
  static/js/components/SiteCollaboratorDrawer.test.tsx
  static/js/components/SiteCollaboratorDrawer.tsx
  static/js/components/SiteCollaboratorEditPanel.test.tsx
  static/js/components/SiteCollaboratorEditPanel.tsx
  static/js/components/SiteCollaboratorList.test.tsx
  static/js/components/SiteCollaboratorList.tsx
  static/js/components/forms/SiteCollaboratorForm.test.tsx
  static/js/components/forms/SiteCollaboratorForm.tsx
  static/js/pages/SitePage.tsx
  static/scss/button.scss
Labels: Waiting on Author

#189 fix a few font-size issues on the site pages
  static/js/components/SiteSidebar.tsx
  static/js/pages/SitePage.test.tsx
  static/js/pages/SitePage.tsx
  static/scss/layout.scss
Labels: Waiting on Author

#183 use the WidgetVariant constants instead of string literals
  static/js/components/forms/SiteAddContentForm.test.tsx
  static/js/components/forms/SiteAddContentForm.tsx
  static/js/components/forms/SiteContentField.test.tsx
  static/js/components/forms/SiteEditContentForm.test.tsx
  static/js/components/forms/validation.test.ts
  static/js/components/forms/validation.ts
  static/js/lib/site_content.test.ts
  static/js/lib/site_content.ts
Labels: Waiting on Author

#197 use textarea for 'Text' type fields, rather than a normal input tag
  static/js/lib/site_content.test.ts
  static/js/lib/site_content.ts
Labels: Waiting on Author

#199 Map fullname to name in social auth
  main/settings.py
  requirements.in
  requirements.txt
Labels: Waiting on Author

#161 Implement conditional fields
  localdev/starters/site-config-override.yml
  static/js/components/SiteSidebar.test.tsx
  static/js/components/forms/SiteAddContentForm.test.tsx
  static/js/components/forms/SiteAddContentForm.tsx
  static/js/components/forms/SiteContentField.tsx
  static/js/components/forms/SiteEditContentForm.test.tsx
  static/js/components/forms/SiteEditContentForm.tsx
  static/js/lib/site_content.test.ts
  static/js/lib/site_content.ts
  static/js/test_util.ts
  static/js/types/websites.ts
  static/js/util/factories/websites.ts
  websites/config_schema/site-config-schema.yml
Labels: Needs Review

#164 Implement hidden field
  localdev/starters/site-config-override.yml
  static/js/lib/site_content.test.ts
  static/js/lib/site_content.ts
  static/js/test_util.ts
  static/js/types/websites.ts
  websites/config_schema/site-config-schema.yml
Labels: Waiting on Author

#207 remove edit links from 'folder' type
  static/js/components/SiteContentListing.test.tsx
  static/js/components/SiteContentListing.tsx
  static/scss/site-page.scss
Labels: Waiting on Author

#175 Added management command to ensure single source of truth for example config files
  .gitignore
  localdev/README.md
  localdev/config_test.py
  localdev/configs/__init__.py
  localdev/configs/api.py
  localdev/configs/api_test.py
  localdev/configs/ocw-course-site-config.yml
  localdev/management/commands/generate_example_configs.py
  localdev/management/commands/override_site_config.py
  localdev/management/commands/override_site_configs.py
  localdev/starters/README.md
  static/js/resources/ocw-course-site-config.json
  static/js/util/factories/websites.ts
  tsconfig.json
  websites/config_schema/api_test.py
Labels: Needs Review

#206 upgrade ckeditor packages
  .github/workflows/ci.yml
  Dockerfile-node
  jest.config.js
  package.json
  scripts/upgrade_ckeditor.js
  static/js/lib/ckeditor/CKEditor.ts
  yarn.lock
Labels: Waiting on Author

#201 Use SelectField widget for all select fields site-wide
  static/js/components/forms/SiteCollaboratorForm.test.tsx
  static/js/components/forms/SiteCollaboratorForm.tsx
  static/js/components/forms/SiteForm.test.tsx
  static/js/components/forms/SiteForm.tsx
  static/js/components/widgets/SelectField.test.tsx
  static/js/components/widgets/SelectField.tsx
Labels: Needs Review

#210 Create content_sync app
  content_sync/__init__.py
  content_sync/admin.py
  content_sync/apps.py
  content_sync/migrations/__init__.py
  content_sync/models.py
  content_sync/views.py
  main/settings.py
Labels: Waiting on Author

#202 Cleaning up collaborator api
  static/js/types/websites.ts
  static/js/util/factories/websites.ts
  websites/constants.py
  websites/models.py
  websites/permissions.py
  websites/serializers.py
  websites/serializers_test.py
  websites/utils.py
  websites/utils_test.py
  websites/views.py
  websites/views_test.py
Labels: Waiting on Author

#205 Merge add and edit content forms
  localdev/configs/ocw-course-site-config.yml
  static/js/components/SiteAddContent.test.tsx
  static/js/components/SiteAddContent.tsx
  static/js/components/SiteContentEditor.test.tsx
  static/js/components/SiteContentEditor.tsx
  static/js/components/SiteContentListing.test.tsx
  static/js/components/SiteContentListing.tsx
  static/js/components/SiteEditContent.test.tsx
  static/js/components/SiteEditContent.tsx
  static/js/components/forms/SiteAddContentForm.test.tsx
  static/js/components/forms/SiteAddContentForm.tsx
  static/js/components/forms/SiteContentForm.test.tsx
  static/js/components/forms/SiteContentForm.tsx
  static/js/components/forms/SiteEditContentForm.test.tsx
  static/js/components/forms/SiteEditContentForm.tsx
  static/js/lib/site_content.test.ts
  static/js/lib/site_content.ts
  static/js/lib/urls.test.ts
  static/js/lib/urls.ts
  static/js/pages/SitePage.tsx
  static/js/resources/ocw-course-site-config.json
  static/js/types/forms.ts
  static/js/types/websites.ts
  static/scss/layout.scss
Labels: Waiting on Author

#215 Added data model for ContentSyncState
  .github/workflows/ci.yml
  content_sync/api.py
  content_sync/api_test.py
  content_sync/apps.py
  content_sync/migrations/0001_add_content_sync_state.py
  content_sync/migrations/0002_backpopulate_content_sync_state.py
  content_sync/models.py
  content_sync/models_test.py
  content_sync/signals.py
  content_sync/signals_test.py
  docker-compose.yml
  ocw_import/api.py
  ocw_import/api_test.py
  pylintrc
  websites/factories.py
  websites/migrations/0017_rename_filepath.py
  websites/models.py
  websites/models_test.py
Labels: Waiting on Author

#218 Add abstract base class for syncing backends
  content_sync/api.py
  content_sync/api_test.py
  content_sync/backends/__init__.py
  content_sync/backends/base.py
  content_sync/backends/base_test.py
  content_sync/factories.py
  content_sync/migrations/0003_content_sync_state_nullable_content.py
  content_sync/models.py
  content_sync/signals.py
  content_sync/tasks.py
  content_sync/tasks_test.py
  main/settings.py
Labels: Waiting on Author

#214 make links in the markdown editor more obvious
  static/scss/ckeditor.scss
  static/scss/layout.scss
Labels: Waiting on Author

#211 add validation for min and max on select field
  localdev/configs/ocw-course-site-config.yml
  static/js/components/forms/validation.test.ts
  static/js/components/forms/validation.ts
  static/js/lib/site_content.test.ts
  static/js/lib/site_content.ts
  static/js/resources/ocw-course-site-config.json
  static/js/types/websites.ts
  static/js/util/factories/websites.ts
Labels: Waiting on Author

#217 Implemented correct UI for 'files' config items
  localdev/configs/basic-site-config.yml
  main/utils.py
  ocw_import/api.py
  ocw_import/api_test.py
  static/js/components/BasicModal.tsx
  static/js/components/BasicModel.test.tsx
  static/js/components/RepeatableContentListing.test.tsx
  static/js/components/RepeatableContentListing.tsx
  static/js/components/SingletonsContentListing.test.tsx
  static/js/components/SingletonsContentListing.tsx
  static/js/components/SiteContentEditor.test.tsx
  static/js/components/SiteContentEditor.tsx
  static/js/components/SiteContentListing.test.tsx
  static/js/components/SiteContentListing.tsx
  static/js/components/forms/SiteContentForm.test.tsx
  static/js/components/forms/SiteContentForm.tsx
  static/js/lib/site_content.ts
  static/js/lib/urls.test.ts
  static/js/lib/urls.ts
  static/js/lib/util.test.ts
  static/js/query-configs/websites.ts
  static/js/resources/basic-site-config.json
  static/js/selectors/websites.ts
  static/js/test_util.ts
  static/js/types/websites.ts
  static/js/util/factories/websites.ts
  static/scss/layout.scss
  static/scss/site-page.scss
  websites/admin.py
  websites/config_schema/api.py
  websites/config_schema/api_test.py
  websites/config_schema/validators.py
  websites/migrations/0018_rename_uuid_to_text_id.py
  websites/migrations/0019_text_id_charfield.py
  websites/models.py
  websites/serializers.py
  websites/serializers_test.py
  websites/site_config_api.py
  websites/site_config_api_test.py
  websites/views.py
  websites/views_test.py
Labels: Waiting on Author

#229 Added optional 'limit' param to OCW course site import
  README.md
  ocw_import/management/commands/import_ocw_course_sites.py
  ocw_import/tasks.py
  ocw_import/tasks_test.py
Labels: Waiting on Author

#216 Github backend and API wrapper
  .github/workflows/ci.yml
  app.json
  content_sync/api.py
  content_sync/api_test.py
  content_sync/apis/__init__.py
  content_sync/apis/github.py
  content_sync/apis/github_test.py
  content_sync/backends/github.py
  content_sync/backends/github_test.py
  content_sync/conftest.py
  content_sync/decorators.py
  content_sync/signals_test.py
  content_sync/tasks.py
  content_sync/tasks_test.py
  main/features.py
  main/serializers.py
  main/settings.py
  ocw_import/api.py
  ocw_import/api_test.py
  ocw_import/management/commands/import_ocw_course_sites.py
  pytest.ini
  requirements.in
  requirements.txt
  websites/migrations/0020_websitecontent_updated_by.py
  websites/models.py
  websites/serializers.py
  websites/serializers_test.py
  websites/views_test.py
Labels: Waiting on Author

#227 Differentiate between types of user-entered data
  localdev/configs/basic-site-config.yml
  localdev/configs/ocw-course-site-config.yml
  localdev/starters/site-config-override.yml
  static/js/resources/basic-site-config.json
  static/js/resources/ocw-course-site-config.json
  websites/config_schema/site-config-schema.yml
  websites/conftest.py
  websites/constants.py
  websites/factories.py
  websites/management/commands/sync_contents_with_config.py
  websites/migrations/0021_is_page_content_field.py
  websites/models.py
  websites/serializers.py
  websites/serializers_test.py
  websites/site_config_api.py
  websites/site_config_api_test.py
  websites/utils.py
  websites/views.py
  websites/views_test.py
Labels: Waiting on Author

#236 Hide the login button if the user is logged in
  static/js/pages/HomePage.test.tsx
  static/js/pages/HomePage.tsx
Labels: Needs Review

#230 add 'Object' field type
  localdev/configs/ocw-course-site-config.yml
  static/js/components/forms/SiteContentForm.test.tsx
  static/js/components/forms/SiteContentForm.tsx
  static/js/components/forms/validation.test.ts
  static/js/components/forms/validation.ts
  static/js/components/widgets/ObjectField.test.tsx
  static/js/components/widgets/ObjectField.tsx
  static/js/components/widgets/SelectField.tsx
  static/js/lib/site_content.test.ts
  static/js/lib/site_content.ts
  static/js/resources/ocw-course-site-config.json
  static/js/types/forms.ts
  static/js/types/websites.ts
  static/scss/forms.scss
  websites/config_schema/site-config-schema.yml
Labels: Waiting on Author

#231 Moved collaborator view tests
  websites/views_collaborator_test.py
  websites/views_test.py
Labels: Small Change, Waiting on Author
