Repository mitodl/ocw-studio, pull requests merged in 2021-01, with the labels that each got.

#7 Initial models for websites and content
  main/middleware.py
  main/middleware_test.py
  main/settings.py
  main/views.py
  repl.py
  test_requirements.txt
  users/migrations/0001_initial.py
  websites/__init__.py
  websites/admin.py
  websites/constants.py
  websites/migrations/0001_initial.py
  websites/migrations/__init__.py
  websites/models.py
Labels: Waiting on Author

#10 Import ocw-to-hugo output into database
  app.json
  docker-compose.yml
  main/s3_utils.py
  main/s3_utils_test.py
  main/settings.py
  main/utils.py
  main/utils_test.py
  pytest.ini
  requirements.in
  requirements.txt
  test_hugo2ocw/output/content/courses/1-050-engineering-mechanics-i-fall-2007/_index.md
  test_hugo2ocw/output/content/courses/1-050-engineering-mechanics-i-fall-2007/sections/assignments/_index.md
  test_hugo2ocw/output/content/courses/1-050-engineering-mechanics-i-fall-2007/sections/assignments/assn1.md
  test_hugo2ocw/output/content/courses/1-050-engineering-mechanics-i-fall-2007/sections/assignments/assn2.md
  test_hugo2ocw/output/content/courses/1-050-engineering-mechanics-i-fall-2007/sections/calendar.md
  test_hugo2ocw/output/content/courses/1-050-engineering-mechanics-i-fall-2007/sections/lecture-notes/_index.md
  test_hugo2ocw/output/content/courses/1-050-engineering-mechanics-i-fall-2007/sections/lecture-notes/lec1.md
  test_hugo2ocw/output/content/courses/1-050-engineering-mechanics-i-fall-2007/sections/lecture-notes/lec2.md
  test_hugo2ocw/output/content/courses/1-050-engineering-mechanics-i-fall-2007/sections/lecture-notes/related-resources/_index.md
  test_hugo2ocw/output/content/courses/1-050-engineering-mechanics-i-fall-2007/sections/lecture-notes/related-resources/matlab.md
  test_hugo2ocw/output/content/courses/1-050-engineering-mechanics-i-fall-2007/sections/lecture-notes/variables1.md
  test_hugo2ocw/output/content/courses/1-050-engineering-mechanics-i-fall-2007/sections/lecture-notes/variables2.md
  test_hugo2ocw/output/content/courses/1-050-engineering-mechanics-i-fall-2007/sections/lecture-notes/variables3.md
  test_hugo2ocw/output/content/courses/1-050-engineering-mechanics-i-fall-2007/sections/syllabus.md
  test_hugo2ocw/output/content/courses/1-201j-transportation-systems-analysis-demand-and-economics-fall-2008/_index.md
  test_hugo2ocw/output/content/courses/1-201j-transportation-systems-analysis-demand-and-economics-fall-2008/sections/assignments/MIT1_201JF08_hw_1.md
  test_hugo2ocw/output/content/courses/1-201j-transportation-systems-analysis-demand-and-economics-fall-2008/sections/assignments/MIT1_201JF08_hw_2.md
  test_hugo2ocw/output/content/courses/1-201j-transportation-systems-analysis-demand-and-economics-fall-2008/sections/assignments/_index.md
  test_hugo2ocw/output/content/courses/1-201j-transportation-systems-analysis-demand-and-economics-fall-2008/sections/calendar.md
  test_hugo2ocw/output/content/courses/1-201j-transportation-systems-analysis-demand-and-economics-fall-2008/sections/exams/MIT1_201JF08_final.md
  test_hugo2ocw/output/content/courses/1-201j-transportation-systems-analysis-demand-and-economics-fall-2008/sections/exams/MIT1_201JF08_final07.md
  test_hugo2ocw/output/content/courses/1-201j-transportation-systems-analysis-demand-and-economics-fall-2008/sections/exams/MIT1_201JF08_midterm.md
  test_hugo2ocw/output/content/courses/1-201j-transportation-systems-analysis-demand-and-economics-fall-2008/sections/exams/MIT1_201JF08_pricing_prob.md
  test_hugo2ocw/output/content/courses/1-201j-transportation-systems-analysis-demand-and-economics-fall-2008/sections/exams/_index.md
  test_hugo2ocw/output/content/courses/1-201j-transportation-systems-analysis-demand-and-economics-fall-2008/sections/readings.md
  test_hugo2ocw/output/content/courses/1-201j-transportation-systems-analysis-demand-and-economics-fall-2008/sections/syllabus.md
  test_hugo2ocw/output/data/courses/1-050-engineering-mechanics-i-fall-2007.json
  test_hugo2ocw/output/data/courses/1-201j-transportation-systems-analysis-demand-and-economics-fall-2008.json
  test_requirements.txt
  websites/api.py
  websites/api_test.py
  websites/conftest.py
  websites/constants.py
  websites/management/__init__.py
  websites/management/commands/__init__.py
  websites/management/commands/backpopulate_ocw_courses.py
  websites/migrations/0002_websitecontent_hugo_filepath.py
  websites/models.py
  websites/tasks.py
  websites/tasks_test.py
Labels: Waiting on Author

#15 Switch to github actions
  .coveragerc
  .github/workflows/ci.yml
  .travis.yml
  docker-compose-notebook.yml
  docker-compose.yml
  main/settings.py
  pytest.ini
  requirements.txt
  scripts/test/js_test.sh
  scripts/test/python_tests.sh
  test_requirements.txt
  travis/codecov_python.sh
  travis/python_tests.sh
Labels: Waiting on Author

#12 Implement OCW news view
  main/settings.py
  main/urls.py
  news/__init__.py
  news/urls.py
  news/util.py
  news/util_test.py
  news/views.py
  news/views_test.py
  requirements.in
  requirements.txt
Labels: Waiting on Author

#21 Move render_bundle_test.py out of the templatetags folder
  main/render_bundle_test.py
Labels: Needs Review

#22 pgbouncer stunnel is deprecated
  Procfile
Labels: Waiting on Author, bug

#19 API view for new courses
  fixtures/__init__.py
  fixtures/common.py
  main/constants.py
  main/permissions.py
  main/permissions_test.py
  main/settings.py
  main/urls.py
  requirements.in
  requirements.txt
  websites/factories.py
  websites/serializers.py
  websites/serializers_test.py
  websites/urls.py
  websites/views.py
  websites/views_test.py
Labels: Waiting on Author

#26 backpopulate_ocw_courses command modifications
  test_hugo2ocw/output/content/courses/1-201j-transportation-systems-analysis-demand-and-economics-fall-2008/sections/syllabus.md
  websites/api.py
  websites/api_test.py
Labels: Waiting on Author

#29 Set default pull request template
  .github/PULL_REQUEST_TEMPLATE/rfc_template.md
  .github/pull_request_template.md
Labels: Needs Review

#30 Added params to backpopulate_ocw_courses command
  websites/api.py
  websites/management/commands/backpopulate_ocw_courses.py
  websites/tasks.py
  websites/tasks_test.py
  websites/views_test.py
Labels: Waiting on Author
