Repository mitodl/ocw-studio, pull requests merged in 2021-08, with the labels that each got.

#441 add ability to remove items from website collections
  static/js/components/SortableWebsiteCollectionItem.test.tsx
  static/js/components/SortableWebsiteCollectionItem.tsx
  static/js/components/WebsiteCollectionItemsEditor.test.tsx
  static/js/components/WebsiteCollectionItemsEditor.tsx
  static/js/query-configs/website_collections.ts
  static/scss/button.scss
Labels: Waiting on Author

#428 Remove text_id parameter, instead use content_context for MenuField
  static/js/components/forms/MenuItemForm.test.tsx
  static/js/components/forms/MenuItemForm.tsx
  static/js/components/widgets/MenuField.test.tsx
  static/js/components/widgets/MenuField.tsx
  static/js/components/widgets/RelationField.test.tsx
  static/js/components/widgets/RelationField.tsx
  websites/views.py
  websites/views_test.py
Labels: Waiting on Author

#446 Reduce default chunk size for import_ocw_course_sites
  ocw_import/management/commands/import_ocw_course_sites.py
Labels: Waiting on Author

#450 add initial resource widget plugin
  static/js/lib/ckeditor/CKEditor.ts
  static/js/lib/ckeditor/plugins/Markdown.test.ts
  static/js/lib/ckeditor/plugins/MarkdownMediaEmbed.test.ts
  static/js/lib/ckeditor/plugins/SiteContentEmbed.test.ts
  static/js/lib/ckeditor/plugins/SiteContentEmbed.ts
  static/js/lib/ckeditor/plugins/test_util.ts
Labels: Waiting on Author

#444 Adjust get_short_id function
  ocw_import/api.py
  ocw_import/api_test.py
Labels: Waiting on Author

#449 Fix for multiple field types in content_context
  websites/serializers.py
  websites/serializers_test.py
Labels: Waiting on Author

#437 switch site content over to user ModalState
  static/js/components/RepeatableContentListing.test.tsx
  static/js/components/RepeatableContentListing.tsx
  static/js/components/SingletonsContentListing.test.tsx
  static/js/components/SingletonsContentListing.tsx
  static/js/components/SiteContentEditor.test.tsx
  static/js/components/SiteContentEditor.tsx
  static/js/components/WebsiteCollectionEditor.test.tsx
  static/js/components/forms/SiteContentForm.test.tsx
  static/js/components/forms/SiteContentForm.tsx
  static/js/pages/WebsiteCollectionsPage.test.tsx
  static/js/pages/WebsiteCollectionsPage.tsx
  static/js/types/forms.ts
  static/js/types/modal_state.ts
  static/js/types/websites.ts
Labels: Waiting on Author

#460 fix drawer width issue
  static/js/components/SiteContentEditor.test.tsx
  static/js/components/SiteContentEditor.tsx
  static/js/components/SiteContentListing.test.tsx
  static/js/components/SiteContentListing.tsx
  static/js/components/forms/SiteContentForm.test.tsx
  static/js/components/forms/SiteContentForm.tsx
  static/js/lib/site_content.test.ts
  static/js/lib/site_content.ts
Labels: Waiting on Author

#473 check for identifier before accessing it
  ocw_import/api.py
  ocw_import/api_test.py
  test_ocw2hugo/1-050-engineering-mechanics-i-fall-2007/config/_default/menus.yaml
Labels: Waiting on Author

#431 Google Drive integration
  app.json
  gdrive_sync/__init__.py
  gdrive_sync/api.py
  gdrive_sync/api_test.py
  gdrive_sync/apps.py
  gdrive_sync/constants.py
  gdrive_sync/factories.py
  gdrive_sync/migrations/0001_initial.py
  gdrive_sync/migrations/__init__.py
  gdrive_sync/models.py
  gdrive_sync/tasks.py
  gdrive_sync/tasks_test.py
  gdrive_sync/urls.py
  gdrive_sync/views.py
  main/settings.py
  requirements.in
  requirements.txt
Labels: Waiting on Author

#463 some dep upgrades
  package.json
  static/js/lib/ckeditor/plugins/Markdown.ts
  static/js/lib/ckeditor/plugins/test_util.ts
  yarn.lock
Labels: Waiting on Author

#381 Draft/live publish notifications
  app.json
  content_sync/conftest.py
  content_sync/pipelines/concourse.py
  content_sync/pipelines/concourse_test.py
  content_sync/pipelines/definitions/concourse/site-pipeline.yml
  main/settings.py
  requirements.in
  requirements.txt
  websites/messages.py
  websites/models.py
  websites/models_test.py
  websites/permissions.py
  websites/permissions_test.py
  websites/templates/mail/preview_publish_success/body.html
  websites/templates/mail/preview_publish_success/subject.txt
  websites/views.py
  websites/views_test.py
Labels: Work in Progress

#468 add OCW_IMPORT_STARTER_SLUG setting and update included testing config
  app.json
  localdev/configs/ocw-course-site-config.yml
  main/settings.py
  ocw_import/conftest.py
  ocw_import/tasks.py
  ocw_import/tasks_test.py
  static/js/components/SiteSidebar.test.tsx
  static/js/resources/ocw-course-site-config.json
Labels: Waiting on Author

#477 upgrade eslint config, remove some unneeded packages
  package.json
  yarn.lock
Labels: Waiting on Author

#475 add resource embed widget
  localdev/configs/ocw-course-site-config.yml
  package.json
  static/js/components/widgets/MarkdownEditor.test.tsx
  static/js/components/widgets/MarkdownEditor.tsx
  static/js/components/widgets/ResourceEmbedField.test.tsx
  static/js/components/widgets/ResourceEmbedField.tsx
  static/js/hooks/state.test.ts
  static/js/hooks/state.ts
  static/js/lib/ckeditor/CKEditor.ts
  static/js/lib/ckeditor/plugins/ResourceEmbed.test.tsx
  static/js/lib/ckeditor/plugins/ResourceEmbed.ts
  static/js/lib/site_content.test.ts
  static/js/lib/site_content.ts
  static/js/query-configs/websites.ts
  static/js/resources/ocw-course-site-config.json
  static/js/types/websites.ts
  static/scss/_variables.scss
  static/scss/layout.scss
  static/scss/resource-embed-widget.scss
  websites/config_schema/site-config-schema.yml
  yarn.lock
Labels: Waiting on Author

#489 Use yaml.SafeLoader
  conftest.py
  content_sync/apis/github.py
  content_sync/pipelines/concourse.py
  content_sync/serializers.py
  content_sync/serializers_test.py
  localdev/configs/api.py
  localdev/configs/api_test.py
  localdev/management/commands/override_site_config.py
  localdev/management/commands/populate_local_starters.py
  main/admin.py
  ocw_import/api.py
  websites/config_schema/api_test.py
  websites/conftest.py
  websites/factories.py
  websites/migrations/0006_website_config_json.py
  websites/migrations/0028_omnibus_site_config.py
  websites/models.py
Labels: Waiting on Author

#492 Add rule to require one of files or folder in collection schema
  websites/config_schema/validators.py
  websites/config_schema/validators_test.py
Labels: Needs Review

#471 Topics UI and backend
  localdev/configs/ocw-course-site-config.yml
  localdev/management/commands/generate_topics.py
  ocw_import/api.py
  ocw_import/api_test.py
  static/js/components/forms/validation.test.ts
  static/js/components/forms/validation.ts
  static/js/components/widgets/HierarchicalSelectField.test.tsx
  static/js/components/widgets/HierarchicalSelectField.tsx
  static/js/components/widgets/MenuField.tsx
  static/js/lib/site_content.test.ts
  static/js/lib/site_content.ts
  static/js/resources/ocw-course-site-config.json
  static/js/types/websites.ts
  static/scss/site-page.scss
  websites/config_schema/site-config-schema.yml
Labels: Needs Review

#501 Fix attach: "resource"
  localdev/configs/ocw-course-site-config.yml
  static/js/resources/ocw-course-site-config.json
Labels: Needs Review

#507 add resource embed in-editor display
  static/js/components/widgets/EmbeddedResource.test.tsx
  static/js/components/widgets/EmbeddedResource.tsx
  static/js/components/widgets/MarkdownEditor.test.tsx
  static/js/components/widgets/MarkdownEditor.tsx
  static/js/lib/ckeditor/plugins/ResourceEmbed.test.tsx
  static/js/lib/ckeditor/plugins/ResourceEmbed.ts
  static/js/pages/SitePage.test.tsx
  static/js/pages/SitesDashboard.test.tsx
  static/js/pages/WebsiteCollectionsPage.test.tsx
  static/js/selectors/websites.ts
  static/js/util/integration_test_helper.tsx
  static/scss/resource-embed-widget.scss
Labels: Waiting on Author

#509 make UUID check version agnostic by default and add tests
  main/utils.py
  main/utils_test.py
Labels: Waiting on Author

#496 add the get_destination_url helper function and use it for menu urls
  content_sync/serializers.py
  content_sync/serializers_test.py
  content_sync/utils.py
  content_sync/utils_test.py
Labels: Waiting on Author

#498 Hide hidden fields inside object fields
  static/js/components/forms/SiteContentForm.test.tsx
  static/js/components/forms/SiteContentForm.tsx
  static/js/components/forms/validation.test.ts
  static/js/components/forms/validation.ts
  static/js/components/widgets/ObjectField.test.tsx
  static/js/components/widgets/ObjectField.tsx
  static/js/lib/site_content.test.ts
  static/js/lib/site_content.ts
Labels: Needs Review

#513 remove course_id prefix on dirpath of imported course content
  ocw_import/api.py
  ocw_import/api_test.py
Labels: Waiting on Author

#476 gdrive folder creation
  app.json
  gdrive_sync/api.py
  gdrive_sync/api_test.py
  gdrive_sync/management/commands/create_missing_website_video_folders.py
  gdrive_sync/tasks.py
  gdrive_sync/tasks_test.py
  main/settings.py
  websites/serializers.py
Labels: Waiting on Author

#469 Transcode videos with AWS MediaConvert
  app.json
  gdrive_sync/admin.py
  gdrive_sync/api.py
  gdrive_sync/api_test.py
  gdrive_sync/constants.py
  gdrive_sync/factories.py
  gdrive_sync/migrations/0002_drivefile_video.py
  gdrive_sync/models.py
  gdrive_sync/tasks.py
  gdrive_sync/tasks_test.py
  main/constants.py
  main/settings.py
  main/urls.py
  test_videos_webhook/cloudwatch_sns_complete.json
  test_videos_webhook/cloudwatch_sns_error.json
  test_videos_webhook/subscribe.json
  videos/__init__.py
  videos/admin.py
  videos/api.py
  videos/api_test.py
  videos/apps.py
  videos/config/mediaconvert.json
  videos/conftest.py
  videos/constants.py
  videos/factories.py
  videos/migrations/0001_initial.py
  videos/migrations/0002_video_statuses.py
  videos/migrations/__init__.py
  videos/models.py
  videos/urls.py
  videos/views.py
  videos/views_test.py
Labels: Work in Progress

#518 publish instructors
  ocw_import/api.py
  ocw_import/api_test.py
Labels: Waiting on Author

#516 Make starter required for OCW_IMPORT_STARTER_SLUG
  conftest.py
  localdev/management/commands/override_site_config.py
  ocw_import/tasks.py
  pytest.ini
  websites/constants.py
  websites/views_test.py
Labels: Waiting on Author

#526 delete unpublished courses originally imported from ocw-to-hugo
  ocw_import/api.py
  ocw_import/api_test.py
  ocw_import/management/commands/import_ocw_course_sites.py
  ocw_import/tasks.py
Labels: Waiting on Author, Blocker

#523 upgrade @ckeditor packages to 29.1.0, upgrade to webpack5
  Dockerfile-node
  package.json
  requirements.txt
  webpack.config.dev.js
  webpack.config.prod.js
  webpack.config.shared.js
  yarn.lock
Labels: Waiting on Author

#527 Add identifier for external links to import_ocw_course_sites
  main/utils.py
  main/utils_test.py
  ocw_import/api.py
  ocw_import/api_test.py
  websites/constants.py
  websites/serializers.py
Labels: Waiting on Author

#530 Only show "Add resource" button when attach field is set
  static/js/components/widgets/MarkdownEditor.test.tsx
  static/js/components/widgets/MarkdownEditor.tsx
Labels: Needs Review
