Repository mitodl/ocw-studio, pull requests merged in 2022-05, with the labels that each got.

#1289 Fix mass publish command
  content_sync/management/commands/mass_publish.py
  websites/views_test.py
Labels: Needs Review

#1291 Remove stray slash from unpublish pipeline
  content_sync/pipelines/definitions/concourse/remove-unpublished-sites.yml
Labels: Waiting on Author

#1297 Cc/user store
  package.json
  static/js/components/Header.test.tsx
  static/js/components/Header.tsx
  static/js/hooks/redux.ts
  static/js/index.tsx
  static/js/lib/redux_query.ts
  static/js/pages/HomePage.test.tsx
  static/js/pages/HomePage.tsx
  static/js/selectors/websites.ts
  static/js/store/configureStore.ts
  static/js/store/index.ts
  static/js/store/rootReducer.ts
  static/js/store/user/index.ts
  static/js/test_setup.ts
  static/js/testing_utils/IntegrationTestHelper.tsx
  static/js/testing_utils/index.ts
  static/js/types/globals.d.ts
  static/js/types/user.d.ts
  static/js/types/util.ts
  static/js/util/integration_test_helper_old.tsx
  yarn.lock
Labels: Needs Review

#1288 Set up one of the transcoded video outputs to be downloadable
  content_sync/utils.py
  content_sync/utils_test.py
  videos/api.py
  videos/api_test.py
  videos/factories.py
  videos/management/commands/backpopulate_video_downloads.py
  videos/migrations/0005_videojob_job_output.py
  videos/models.py
Labels: Waiting on Author

#1300 redirect to login on authentication failures
  package.json
  static/js/components/AuthenticationAlert.test.tsx
  static/js/components/AuthenticationAlert.tsx
  static/js/components/Dialog.test.tsx
  static/js/components/Dialog.tsx
  static/js/components/SiteCollaboratorList.test.tsx
  static/js/components/SiteCollaboratorList.tsx
  static/js/components/widgets/MenuField.tsx
  static/js/components/widgets/RelationField.test.tsx
  static/js/components/widgets/ResourcePickerDialog.tsx
  static/js/components/widgets/WebsiteCollectionField.test.tsx
  static/js/hooks/websites.test.ts
  static/js/lib/urls.ts
  static/js/pages/App.tsx
  static/js/pages/HomePage.test.tsx
  static/js/pages/SitesDashboard.test.tsx
  static/js/store/configureStore.ts
  static/js/store/index.ts
  static/js/store/middleware/authFailureMiddleware.ts
  static/js/store/rootReducer.ts
  static/js/store/user/index.ts
  static/js/test_setup.ts
  static/js/test_util.ts
  static/js/testing_utils/IntegrationTestHelper.tsx
  static/js/util/factories/websites.ts
  yarn.lock
Labels: Waiting on Author

#1302 fix webvtt transcript
  videos/management/commands/clear_webvtt_files.py
  videos/threeplay_api.py
  videos/threeplay_api_test.py
Labels: Needs Review

#1304 make legacy uid hidden
  localdev/configs/ocw-course-site-config.yml
  static/js/resources/ocw-course-site-config.json
Labels: Waiting on Author

#1306 add SITEMAP_DOMAIN to the app and pipeline templates
  app.json
  content_sync/pipelines/concourse.py
  content_sync/pipelines/definitions/concourse/mass-build-sites.yml
  content_sync/pipelines/definitions/concourse/site-pipeline.yml
  main/settings.py
Labels: Waiting on Author

#1312 migrate ocw-www content type pages to page
  websites/migrations/0048_www_pages_to_page.py
Labels: Needs Review

#1309 Added a github action workflow for releasing to CI
  .github/workflows/release-candiate.yml
Labels: Needs Review

#1310 updated node version
  docker-compose.yml
  package.json
Labels: Waiting on Author

#1319 Fix workflow syntax
  .github/workflows/release-candiate.yml
Labels: Waiting on Author

#1321 specify docker container version for mitodl/ocw-course-publisher
  content_sync/pipelines/definitions/concourse/site-pipeline.yml
  content_sync/pipelines/definitions/concourse/theme-assets-pipeline.yml
Labels: Waiting on Author

#1326 use the proper ocw-course-publisher image and specify version in mass-build-sites
  content_sync/pipelines/definitions/concourse/mass-build-sites.yml
Labels: Needs Review

#1329 add API_BEARER_TOKEN to the Hugo step in the site build pipelines
  content_sync/pipelines/definitions/concourse/mass-build-sites.yml
  content_sync/pipelines/definitions/concourse/site-pipeline.yml
Labels: Needs Review

#1325 Fix deployment configuration
  .github/workflows/release-candiate.yml
Labels: Needs Review

#1313 make retry_on_failure preserve type hints
  content_sync/decorators.py
Labels: Waiting on Author, Small Change

#1331 Added a github action for production releases.
  .github/workflows/production.yml
Labels: Waiting on Author

#1333 Update the prod deploy script to point to prod
  .github/workflows/production.yml
Labels: Needs Review

#1341 Fix MIT logo link
  static/js/components/Header.tsx
Labels: Waiting on Author, Small Change

#1332 Hid Site Dashboard and refactored component
  static/js/components/ErrorComponent.tsx
  static/js/components/NotFound.tsx
  static/js/components/util/PrivateRoute.tsx
  static/js/lib/urls.ts
  static/js/pages/App.test.tsx
  static/js/pages/App.tsx
Labels: Waiting on Author

#1347 improve frontend shortcode regex to not be fooled by delimiters in shortcode args
  static/js/lib/ckeditor/plugins/ResourceEmbed.ts
  static/js/lib/ckeditor/plugins/ResourceLinkMarkdownSyntax.ts
  static/js/lib/ckeditor/plugins/util.test.ts
  static/js/lib/ckeditor/plugins/util.ts
Labels: Waiting on Author

#1345 check for 3play completion
  videos/threeplay_api.py
  videos/threeplay_api_test.py
Labels: Waiting on Author

#1351 make markdown editor minimal by default
  static/js/lib/site_content.test.ts
  static/js/lib/site_content.ts
Labels: Needs Review

#1359 treat shortcodes in resource link text as literal text
  static/js/lib/ckeditor/plugins/ResourceLinkMarkdownSyntax.test.ts
  static/js/lib/ckeditor/plugins/ResourceLinkMarkdownSyntax.ts
  static/js/lib/ckeditor/plugins/util.ts
Labels: Waiting on Author

#1349 improve legacy shortcode handling
  static/js/lib/ckeditor/plugins/LegacyShortcodes.test.ts
  static/js/lib/ckeditor/plugins/LegacyShortcodes.ts
  static/js/lib/ckeditor/plugins/util.test.ts
  static/js/lib/ckeditor/plugins/util.ts
Labels: Waiting on Author

#1316 Customizable URLs for studio
  content_sync/api.py
  content_sync/api_test.py
  content_sync/pipelines/concourse.py
  content_sync/pipelines/concourse_test.py
  content_sync/pipelines/definitions/concourse/mass-build-sites.yml
  content_sync/pipelines/definitions/concourse/site-pipeline.yml
  content_sync/serializers.py
  content_sync/serializers_test.py
  localdev/configs/ocw-course-site-config.yml
  main/settings.py
  static/js/components/PublishDrawer.test.tsx
  static/js/components/PublishDrawer.tsx
  static/js/components/forms/PublishForm.test.tsx
  static/js/components/forms/PublishForm.tsx
  static/js/constants.ts
  static/js/query-configs/websites.ts
  static/js/resources/ocw-course-site-config.json
  static/js/types/websites.ts
  static/js/util/factories/websites.ts
  videos/api.py
  videos/api_test.py
  websites/api.py
  websites/api_test.py
  websites/config_schema/site-config-schema.yml
  websites/conftest.py
  websites/constants.py
  websites/factories.py
  websites/migrations/0049_website_url_path.py
  websites/models.py
  websites/models_test.py
  websites/serializers.py
  websites/serializers_test.py
  websites/site_config_api.py
  websites/views.py
  websites/views_test.py
Labels: Needs Review

#1358 Added slack notifications on_failure cases to the individual site pipelines.
  content_sync/pipelines/definitions/concourse/site-pipeline.yml
Labels: enhancement, Waiting on Author, DevOps, Small Change

#1256 added command to update departments
  websites/management/commands/update_departments.py
Labels: Waiting on Author

#1371 Custom URL tweaks
  static/js/components/forms/PublishForm.tsx
  static/js/components/widgets/RelationField.test.tsx
  static/js/components/widgets/RelationField.tsx
  static/js/components/widgets/WebsiteCollectionField.test.tsx
  static/js/components/widgets/WebsiteCollectionField.tsx
  static/js/types/websites.ts
  static/js/util/factories/websites.ts
  videos/tasks.py
  videos/tasks_test.py
  websites/migrations/0050_modify_course_lists.py
  websites/models.py
  websites/models_test.py
  websites/serializers.py
  websites/serializers_test.py
Labels: Needs Review

#1364 allow setting link / embed on minimal markdown editor
  static/js/components/widgets/MarkdownEditor.tsx
  static/js/lib/ckeditor/CKEditor.ts
Labels: Waiting on Author

#1355 feat: Limit site starter options when creating new site
  requirements.in
  requirements.txt
  static/js/components/forms/SiteForm.tsx
  static/js/constants.ts
  static/js/types/websites.ts
  static/js/util/factories/websites.ts
  websites/admin.py
  websites/constants.py
  websites/factories.py
  websites/migrations/0049_websitestarter_status.py
  websites/migrations/0050_merge_20220524_0942.py
  websites/models.py
  websites/serializers.py
  websites/serializers_test.py
  websites/views.py
  websites/views_test.py
Labels: Waiting on Author

#1377 Show proper urls on the Publish Drawer
  static/js/components/forms/PublishForm.test.tsx
  static/js/components/forms/PublishForm.tsx
  websites/models.py
  websites/models_test.py
Labels: Waiting on Author

#1382 move resource description to markdown body
  websites/migrations/0052_resource_description_to_body.py
Labels: Waiting on Author
