Repository mitodl/ocw-studio, pull requests merged in 2022-12, with the labels that each got.

#1594 More Github Actions yml changes (ubuntu-latest to ubuntu-20.04)
  .github/workflows/ci.yml
  .github/workflows/production.yml
  .github/workflows/release-candiate.yml
Labels: Waiting on Author

#1588 Subscripts and superscripts
  static/js/components/widgets/MarkdownEditor.test.tsx
  static/js/components/widgets/MarkdownEditor.tsx
  static/js/lib/ckeditor/CKEditor.ts
  static/js/lib/ckeditor/plugins/Markdown.test.ts
  static/js/lib/ckeditor/plugins/Markdown.ts
  static/js/lib/ckeditor/plugins/MarkdownConfigPlugin.ts
  static/js/lib/ckeditor/plugins/MarkdownSyntaxPlugin.ts
  static/js/lib/ckeditor/plugins/ResourceLinkMarkdownSyntax.test.ts
  static/js/lib/ckeditor/plugins/ResourceLinkMarkdownSyntax.ts
  static/js/lib/ckeditor/plugins/constants.ts
  static/js/lib/ckeditor/plugins/test_util.ts
  static/js/lib/ckeditor/turndown.ts
  static/js/lib/site_content.test.ts
  static/js/lib/site_content.ts
  static/js/pages/MarkdownEditorTestPage.tsx
  static/js/types/ckeditor.d.ts
  static/js/types/ckeditor_markdown.ts
  static/js/types/websites.ts
  websites/config_schema/site-config-schema.yml
Labels: Waiting on Author

#1597 Revert "Subscripts and superscripts"
  static/js/components/widgets/MarkdownEditor.test.tsx
  static/js/components/widgets/MarkdownEditor.tsx
  static/js/lib/ckeditor/CKEditor.ts
  static/js/lib/ckeditor/plugins/Markdown.test.ts
  static/js/lib/ckeditor/plugins/Markdown.ts
  static/js/lib/ckeditor/plugins/MarkdownConfigPlugin.ts
  static/js/lib/ckeditor/plugins/MarkdownSyntaxPlugin.ts
  static/js/lib/ckeditor/plugins/ResourceLinkMarkdownSyntax.test.ts
  static/js/lib/ckeditor/plugins/ResourceLinkMarkdownSyntax.ts
  static/js/lib/ckeditor/plugins/constants.ts
  static/js/lib/ckeditor/plugins/test_util.ts
  static/js/lib/ckeditor/turndown.ts
  static/js/lib/site_content.test.ts
  static/js/lib/site_content.ts
  static/js/pages/MarkdownEditorTestPage.tsx
  static/js/types/ckeditor.d.ts
  static/js/types/ckeditor_markdown.ts
  static/js/types/websites.ts
  websites/config_schema/site-config-schema.yml
Labels: Needs Review

#1380 update content dispositions
  content_sync/utils.py
  gdrive_sync/api.py
  gdrive_sync/api_test.py
  gdrive_sync/management/commands/update_content_disposition.py
  main/s3_utils.py
  videos/api.py
  videos/api_test.py
  videos/constants.py
  videos/management/commands/clear_webvtt_files.py
  videos/models.py
Labels: Needs Review

#1604 Modify RelationField to filter out unpublished content if the website property is present
  static/js/components/widgets/RelationField.test.tsx
  static/js/components/widgets/RelationField.tsx
Labels: Waiting on Author

#1611 clean publish for individual sites
  content_sync/pipelines/concourse_test.py
  content_sync/pipelines/definitions/concourse/site-pipeline.yml
Labels: Waiting on Author

#1616 themes branch argument for theme assets build
  content_sync/api.py
  content_sync/management/commands/upsert_theme_assets_pipeline.py
  content_sync/pipelines/concourse.py
  content_sync/pipelines/concourse_test.py
  content_sync/tasks.py
Labels: Waiting on Author

#1618 update ckeditor to v35
  package.json
  static/js/test_setup.ts
  yarn.lock
Labels: Needs Review, Blocker

#1623 purge cache on build failures; add alerts
  content_sync/pipelines/definitions/concourse/mass-build-sites.yml
Labels: Needs Review

#1617 Subscript and Superscript support in CKEditor
  static/js/components/widgets/MarkdownEditor.test.tsx
  static/js/components/widgets/MarkdownEditor.tsx
  static/js/lib/ckeditor/CKEditor.ts
  static/js/lib/ckeditor/plugins/Markdown.test.ts
  static/js/lib/ckeditor/plugins/Markdown.ts
  static/js/lib/ckeditor/plugins/MarkdownConfigPlugin.ts
  static/js/lib/ckeditor/plugins/MarkdownSyntaxPlugin.ts
  static/js/lib/ckeditor/plugins/ResourceLinkMarkdownSyntax.test.ts
  static/js/lib/ckeditor/plugins/ResourceLinkMarkdownSyntax.ts
  static/js/lib/ckeditor/plugins/constants.ts
  static/js/lib/ckeditor/plugins/test_util.ts
  static/js/lib/ckeditor/turndown.ts
  static/js/lib/site_content.test.ts
  static/js/lib/site_content.ts
  static/js/pages/MarkdownEditorTestPage.tsx
  static/js/types/ckeditor.d.ts
  static/js/types/ckeditor_markdown.ts
  static/js/types/websites.ts
  websites/config_schema/site-config-schema.yml
Labels: Waiting on Author

#1627 Cc/disallow simul subsup
  package.json
  static/js/components/widgets/MarkdownEditor.tsx
  static/js/lib/ckeditor/CKEditor.ts
  static/js/lib/ckeditor/attributeChecks.ts
  static/js/lib/ckeditor/plugins/DisallowNestedTables.ts
  static/js/lib/ckeditor/plugins/LegacyShortcodes.ts
  static/js/lib/ckeditor/plugins/Markdown.ts
  static/js/lib/ckeditor/plugins/MarkdownConfigPlugin.ts
  static/js/lib/ckeditor/plugins/MarkdownSyntaxPlugin.ts
  static/js/lib/ckeditor/plugins/ResourceEmbed.ts
  static/js/lib/ckeditor/plugins/ResourceLinkMarkdownSyntax.ts
  static/js/lib/ckeditor/plugins/test_util.ts
  static/js/test_util.ts
  yarn.lock
Labels: Waiting on Author

#1629 abort onReady if no editor
  static/js/components/widgets/MarkdownEditor.tsx
Labels: Waiting on Author
