Repository mitodl/ocw-studio, pull requests merged in 2022-04, with the labels that each got.

#1187 Added some metrics for celery task completion time
  main/celery.py
Labels: Waiting on Author

#1192 tolerate href, href_uid on resource shortcode
  .gitignore
  package.json
  static/js/components/StudioList.tsx
  static/js/components/widgets/MarkdownEditor.test.tsx
  static/js/components/widgets/MarkdownEditor.tsx
  static/js/lib/ckeditor/plugins/ResourceEmbed.test.tsx
  static/js/lib/ckeditor/plugins/ResourceEmbed.ts
  static/js/lib/ckeditor/plugins/test_util.ts
  static/js/lib/ckeditor/plugins/util.spec.ts
  static/js/lib/ckeditor/plugins/util.ts
  static/js/query-configs/websites.ts
  static/js/types/ckeditor.d.ts
  static/js/util/index.ts
  static/js/util/integration_test_helper.tsx
  yarn.lock
Labels: Waiting on Author

#1169 Get gdrive file body via the google drive api and stream that to s3
  gdrive_sync/api.py
  gdrive_sync/api_test.py
Labels: Waiting on Author

#1196 Handle courses with no instructors
  websites/serializers.py
  websites/serializers_test.py
Labels: Waiting on Author

#1199 Update fastly vars for mass-publish pipeline definition
  content_sync/pipelines/definitions/concourse/mass-publish.yml
Labels: Needs Review

#1204 Sort websites by first_published_to_production
  websites/factories.py
  websites/serializers.py
  websites/views.py
  websites/views_test.py
Labels: Needs Review

#1206 Cc/convert link wrapped images
  websites/management/commands/markdown_cleaning/baseurl_rule.py
  websites/management/commands/markdown_cleaning/baseurl_rule_test.py
  websites/management/commands/markdown_cleaning/link_parser_test.py
  websites/management/commands/markdown_cleaning/link_wrapped_images.py
  websites/management/commands/markdown_cleaning/link_wrapped_images_test.py
  websites/management/commands/markdown_cleaning/ocwnext_rule.py
  websites/management/commands/markdown_cleaning/parsing_utils.py
  websites/management/commands/markdown_cleaning/parsing_utils_test.py
  websites/management/commands/markdown_cleaning/resolveuid_rule.py
  websites/management/commands/markdown_cleaning/resolveuid_rule_test.py
  websites/management/commands/markdown_cleaning/rootrelative_urls_test.py
  websites/management/commands/markdown_cleaning/shortcode_grammar.py
  websites/management/commands/markdown_cleaning/shortcode_grammar_test.py
  websites/management/commands/markdown_cleaning/shortcode_logging_rule.py
  websites/management/commands/markdown_cleaning/testing_utils.py
  websites/management/commands/markdown_cleaning/utils.py
  websites/management/commands/markdown_cleaning/utils_test.py
  websites/management/commands/markdown_cleanup.py
Labels: Waiting on Author

#1210 add "other" tab to resource picker
  static/js/components/RepeatableContentListing.tsx
  static/js/components/widgets/ResourcePickerDialog.test.tsx
  static/js/components/widgets/ResourcePickerDialog.tsx
  static/js/components/widgets/ResourcePickerListing.test.tsx
  static/js/components/widgets/ResourcePickerListing.tsx
  static/js/util/index.test.ts
  static/js/util/index.ts
  static/js/util/websites.ts
  static/scss/common.scss
Labels: Waiting on Author

#1214 prevent mass import
  ocw_import/api.py
  ocw_import/management/commands/import_ocw_course_sites.py
  ocw_import/tasks.py
  ocw_import/tasks_test.py
Labels: Waiting on Author

#1216 Cc/default active tab
  static/js/components/widgets/ResourcePickerDialog.test.tsx
  static/js/components/widgets/ResourcePickerDialog.tsx
  websites/management/commands/markdown_cleaning/link_logging_rule.py
  websites/management/commands/markdown_cleaning/parsing_utils.py
  websites/management/commands/markdown_cleaning/shortcode_grammar_test.py
Labels: Waiting on Author

#1226 Cc/fix pagination
  package.json
  static/js/components/PaginationControls.tsx
  static/js/components/RepeatableContentListing.test.tsx
  static/js/components/RepeatableContentListing.tsx
  static/js/hooks/search.ts
  static/js/pages/SitesDashboard.test.tsx
  static/js/pages/SitesDashboard.tsx
  static/js/types/types.spec.ts
  static/js/util/integration_test_helper.tsx
  yarn.lock
Labels: Waiting on Author

#1219 Avoid unnecessary dupe transcode jobs, retry on gdrive->s3 upload errors a few times before raising
  gdrive_sync/api.py
  gdrive_sync/api_test.py
  videos/api.py
  videos/api_test.py
  videos/views_test.py
Labels: Waiting on Author

#1227 Sync videos from Google Drive files_final folder, don't transcode or upload to Youtube
  gdrive_sync/api.py
  gdrive_sync/api_test.py
  gdrive_sync/models.py
  gdrive_sync/tasks_test.py
Labels: Needs Review

#1229 Change the mass-publish API endpoint filter
  websites/views.py
  websites/views_test.py
Labels: Waiting on Author

#1234 remove delete_unpublished_courses
  ocw_import/management/commands/import_ocw_course_sites.py
  ocw_import/tasks.py
  ocw_import/tasks_test.py
Labels: bug, Needs Review

#1235 improve link logging
  websites/management/commands/markdown_cleaning/cleaner.py
  websites/management/commands/markdown_cleaning/link_logging_rule.py
  websites/management/commands/markdown_cleaning/validate_urls.py
  websites/management/commands/markdown_cleanup.py
Labels: Waiting on Author

#1240 fix: required=true for relation widgetvariant
  static/js/components/forms/validation.ts
  static/js/constants.ts
Labels: Waiting on Author

#1239 fix: course_collections renamed to course-collection
  localdev/configs/ocw-www.yml
  static/js/components/widgets/ResourcePickerDialog.tsx
  static/js/components/widgets/ResourcePickerListing.test.tsx
  static/js/constants.ts
  static/js/resources/ocw-www.json
Labels: Waiting on Author

#1241 [markdown cleanup] fix superscript/subscript escaping issues
  websites/management/commands/markdown_cleaning/cleanup_rule.py
  websites/management/commands/markdown_cleaning/subsup_fixes.py
  websites/management/commands/markdown_cleaning/subsup_fixes_test.py
  websites/management/commands/markdown_cleanup.py
Labels: Waiting on Author

#1246 Rename mass-publish pipeline to mass-build-sites, refactor mass-publish command
  content_sync/api.py
  content_sync/api_test.py
  content_sync/management/commands/mass_publish.py
  content_sync/management/commands/upsert_mass_build_pipeline.py
  content_sync/pipelines/base.py
  content_sync/pipelines/concourse.py
  content_sync/pipelines/concourse_test.py
  content_sync/pipelines/definitions/concourse/mass-build-sites.yml
  content_sync/tasks.py
  content_sync/tasks_test.py
  main/celery.py
  websites/urls.py
  websites/views.py
  websites/views_test.py
Labels: Waiting on Author

#1245 [markdown cleanup] <, > to «, »
  websites/management/commands/markdown_cleaning/__init__.py
  websites/management/commands/markdown_cleaning/parsing_utils.py
  websites/management/commands/markdown_cleaning/parsing_utils_test.py
  websites/management/commands/markdown_cleaning/rules/__init__.py
  websites/management/commands/markdown_cleaning/rules/baseurl.py
  websites/management/commands/markdown_cleaning/rules/baseurl_test.py
  websites/management/commands/markdown_cleaning/rules/link_logging.py
  websites/management/commands/markdown_cleaning/rules/link_unescape.py
  websites/management/commands/markdown_cleaning/rules/link_unescape_test.py
  websites/management/commands/markdown_cleaning/rules/link_wrapped_images.py
  websites/management/commands/markdown_cleaning/rules/link_wrapped_images_test.py
  websites/management/commands/markdown_cleaning/rules/metadata_relative_urls.py
  websites/management/commands/markdown_cleaning/rules/metadata_relative_urls_test.py
  websites/management/commands/markdown_cleaning/rules/removals.py
  websites/management/commands/markdown_cleaning/rules/resource_link_nextprev.py
  websites/management/commands/markdown_cleaning/rules/resource_link_nextprev_test.py
  websites/management/commands/markdown_cleaning/rules/rootrelative_urls.py
  websites/management/commands/markdown_cleaning/rules/rootrelative_urls_test.py
  websites/management/commands/markdown_cleaning/rules/shortcode_logging.py
  websites/management/commands/markdown_cleaning/rules/shortcode_logging_test.py
  websites/management/commands/markdown_cleaning/rules/subsup_fixes.py
  websites/management/commands/markdown_cleaning/rules/subsup_fixes_test.py
  websites/management/commands/markdown_cleaning/rules/validate_urls.py
  websites/management/commands/markdown_cleaning/shortcode_parser.py
  websites/management/commands/markdown_cleaning/shortcode_parser_test.py
  websites/management/commands/markdown_cleanup.py
Labels: Waiting on Author

#1249 Escape quotes in resource link text
  static/js/lib/ckeditor/plugins/ResourceEmbed.test.tsx
  static/js/lib/ckeditor/plugins/ResourceLinkMarkdownSyntax.test.ts
  static/js/lib/ckeditor/plugins/ResourceLinkMarkdownSyntax.ts
  static/js/lib/ckeditor/plugins/util.spec.ts
  static/js/lib/ckeditor/plugins/util.ts
  static/js/util/index.ts
  websites/management/commands/markdown_cleaning/parsing_utils.py
  websites/management/commands/markdown_cleaning/parsing_utils_test.py
Labels: Waiting on Author

#1253 set `YT_FIELD_DESCRIPTION` to `video_metadata.youtube_description`
  main/settings.py
  main/utils.py
  videos/youtube_test.py
  websites/api.py
  websites/api_test.py
Labels: Waiting on Author

#1244 Sync Website.title with the sitemetadata course_title
  app.json
  main/settings.py
  static/js/types/websites.ts
  static/js/util/factories/websites.ts
  websites/api.py
  websites/serializers.py
  websites/serializers_test.py
Labels: Waiting on Author

#1250 added command to migrate testimonials to stories
  websites/management/commands/update_content_fields.py
Labels: Waiting on Author

#1202 New sites API: Filter out sites without sitemetadata content instead of Website.metadata
  websites/views.py
  websites/views_test.py
Labels: Waiting on Author

#1263 Cc/navigation prompts
  package.json
  static/js/components/ConfirmationModal.test.tsx
  static/js/components/ConfirmationModal.tsx
  static/js/components/RepeatableContentListing.test.tsx
  static/js/components/SingletonsContentListing.test.tsx
  static/js/components/SingletonsContentListing.tsx
  static/js/components/SiteContentEditorDrawer.test.tsx
  static/js/components/SiteContentEditorDrawer.tsx
  static/js/components/util/ConfirmDiscardChanges.tsx
  static/js/components/util/Prompt.tsx
  static/js/components/util/Spinner.tsx
  static/js/hooks/confirmation.test.ts
  static/js/hooks/confirmation.ts
  static/js/lib/ckeditor/plugins/ResourceLinkMarkdownSyntax.ts
  static/js/lib/ckeditor/plugins/util.ts
  static/js/pages/SitePage.test.tsx
  static/js/pages/SitePage.tsx
  static/js/pages/SitesDashboard.test.tsx
  static/js/query-configs/websites.ts
  static/js/test_setup.ts
  static/js/test_util.ts
  static/js/util/integration_test_helper.tsx
  static/scss/layout.scss
  yarn.lock
Labels: Needs Review

#1257 Added a check to return as soon as filter_set has been gone over
  ocw_import/api.py
Labels: Needs Review

#1273 Added video-gallery to add link ResourceDialogPicker
  static/js/components/widgets/ResourcePickerDialog.tsx
  static/js/constants.ts
Labels: Needs Review

#1279 fix erroneous prompting when saving new pages
  static/js/components/SiteContentEditor.test.tsx
  static/js/components/SiteContentEditor.tsx
Labels: Needs Review

#1281 fix transcript links
  videos/tasks.py
  videos/tasks_test.py
Labels: Waiting on Author

#1261 Fix file paths command
  websites/management/commands/fix_file_urls.py
Labels: Waiting on Author

#1276 add migration to move filetype to resourcetype
  websites/migrations/0046_filetype_to_resourcetype.py
Labels: Waiting on Author

#1270 Unpublish sites - backend code
  content_sync/api.py
  content_sync/api_test.py
  content_sync/management/commands/mass_publish.py
  content_sync/management/commands/upsert_site_removal_pipeline.py
  content_sync/pipelines/base.py
  content_sync/pipelines/concourse.py
  content_sync/pipelines/concourse_test.py
  content_sync/pipelines/definitions/concourse/remove-unpublished-sites.yml
  content_sync/tasks.py
  content_sync/tasks_test.py
  docker-compose.yml
  websites/admin.py
  websites/api.py
  websites/api_test.py
  websites/factories.py
  websites/migrations/0044_add_website__first_published_to_production.py
  websites/migrations/0046_unpublish_fields.py
  websites/models.py
  websites/serializers.py
  websites/serializers_test.py
  websites/urls.py
  websites/views.py
  websites/views_test.py
Labels: Waiting on Author

#1266 specify yarn version for heroku
  package.json
Labels: Waiting on Author

#1284 minor update to social auth readme section
  README.md
Labels: Waiting on Author
