Repository mitodl/ocw-studio, pull requests merged in 2022-06, with the labels that each got.

#1385 Pipeline failure alerting - Part 2
  content_sync/pipelines/definitions/concourse/site-pipeline.yml
Labels: DevOps

#1390 Management command & github api tweak to ensure checksums are current
  content_sync/apis/github.py
  content_sync/apis/github_test.py
  content_sync/management/commands/update_checksums.py
  websites/serializers.py
Labels: Needs Review

#1383 Always set publish fields in publish_website function
  content_sync/api.py
  content_sync/api_test.py
Labels: Needs Review

#1397 Updating nginx version in docker-compose.yml to 1.22.0
  docker-compose.yml
Labels: Waiting on Author

#1293 do not emit declaration files
  tsconfig.json
Labels: Waiting on Author, Small Change

#1367 Show publishing api errors in publishing drawer
  static/js/components/PublishDrawer.test.tsx
  static/js/components/PublishDrawer.tsx
  static/js/components/forms/PublishForm.test.tsx
  static/js/components/forms/PublishForm.tsx
  static/js/constants.ts
  static/js/query-configs/websites.ts
  static/js/testing_utils/IntegrationTestHelper.tsx
  websites/serializers.py
  websites/serializers_test.py
Labels: Waiting on Author

#1363 update generate_item_metadata to optionally use config default value
  gdrive_sync/api.py
  gdrive_sync/api_test.py
  localdev/configs/basic-site-config.yml
  static/js/resources/basic-site-config.json
  videos/tasks_test.py
  websites/management/commands/update_content_metadata.py
  websites/site_config_api.py
  websites/site_config_api_test.py
Labels: Waiting on Author

#1392 Option to delete existing pipelines in management commands
  content_sync/api.py
  content_sync/api_test.py
  content_sync/management/commands/backpopulate_pipelines.py
  content_sync/management/commands/upsert_mass_build_pipeline.py
  content_sync/management/commands/upsert_site_removal_pipeline.py
  content_sync/management/commands/upsert_theme_assets_pipeline.py
  content_sync/pipelines/base.py
  content_sync/pipelines/concourse.py
  content_sync/pipelines/concourse_test.py
  content_sync/tasks.py
  content_sync/tasks_test.py
  ocw_import/management/commands/repair_dupe_repos.py
Labels: Waiting on Author

#1400 Remove log statement
  content_sync/pipelines/concourse.py
Labels: Waiting on Author

#1394 Use common mgmt command options for filtering by websites
  content_sync/management/commands/backpopulate_pipelines.py
  content_sync/management/commands/mass_publish.py
  content_sync/management/commands/reset_sync_states.py
  content_sync/management/commands/sync_backend_to_db.py
  content_sync/management/commands/sync_website_to_backend.py
  content_sync/management/commands/update_checksums.py
  content_sync/management/commands/upsert_mass_build_pipeline.py
  content_sync/management/commands/upsert_site_removal_pipeline.py
  content_sync/management/commands/upsert_theme_assets_pipeline.py
  main/management/__init__.py
  main/management/commands/__init__.py
  main/management/commands/filter.py
  ocw_import/management/commands/import_ocw_course_sites.py
  ocw_import/management/commands/overwrite_ocw_course_content.py
  ocw_import/management/commands/repair_dupe_repos.py
  videos/management/commands/backpopulate_video_downloads.py
  websites/api.py
  websites/api_test.py
  websites/management/commands/backpopulate_groups.py
  websites/management/commands/fix_file_urls.py
  websites/management/commands/markdown_cleanup.py
  websites/management/commands/sync_content_state.py
  websites/management/commands/sync_contents_with_config.py
  websites/management/commands/update_content_fields.py
  websites/management/commands/update_content_metadata.py
  websites/management/commands/update_departments.py
Labels: Waiting on Author

#1389 Added permission hook for conditional rendering
  main/views.py
  main/views_test.py
  static/js/constants.ts
  static/js/hooks/permissions.ts
  static/js/pages/SitesDashboard.tsx
  static/js/test_setup.ts
  static/js/types/user.d.ts
Labels: Waiting on Author

#1402 Add management command to assist in populating default license values
  main/management/commands/filter.py
  websites/management/commands/set_content_metadata_to_default.py
Labels: Waiting on Author

#1408 Fixed IO exception for command sync_website_to_backend
  content_sync/management/commands/sync_website_to_backend.py
Labels: Waiting on Author

#1406 Add Filename to Edit Resource Menu When GDrive Sync Enabled
  static/js/components/forms/SiteContentForm.test.tsx
  static/js/components/forms/SiteContentForm.tsx
  static/js/components/widgets/FileUploadField.test.tsx
  static/js/components/widgets/Label.tsx
  static/js/lib/util.test.ts
  static/js/lib/util.ts
Labels: Needs Review

#1405 Added a check for site status
  static/js/pages/SitesDashboard.tsx
  static/js/types/websites.ts
  static/js/util/factories/websites.ts
  websites/serializers.py
Labels: Waiting on Author
