Repository mitodl/ocw-studio, pull requests merged in 2022-03, with the labels that each got.

#1067 change resource_link delimiters to % instead of < >
  static/js/lib/ckeditor/plugins/ResourceLinkMarkdownSyntax.test.ts
  static/js/lib/ckeditor/plugins/ResourceLinkMarkdownSyntax.ts
  websites/management/commands/markdown_cleaning/baseurl_rule.py
  websites/management/commands/markdown_cleaning/baseurl_rule_test.py
  websites/management/commands/markdown_cleaning/resource_link_delimiters.py
  websites/management/commands/markdown_cleaning/resource_link_delimiters_test.py
  websites/management/commands/markdown_cleanup.py
Labels: Needs Review

#1072 move website content drawer open / close / edit state to URL
  package.json
  static/js/components/ConfirmationModal.test.tsx
  static/js/components/ConfirmationModal.tsx
  static/js/components/RepeatableContentListing.test.tsx
  static/js/components/RepeatableContentListing.tsx
  static/js/components/SiteContentEditorDrawer.test.tsx
  static/js/components/SiteContentEditorDrawer.tsx
  static/js/components/SiteContentListing.test.tsx
  static/js/components/SiteContentListing.tsx
  static/js/components/SiteSidebar.tsx
  static/js/hooks/confirmation.ts
  static/js/lib/urls.test.ts
  static/js/lib/urls.ts
  static/js/pages/App.tsx
  static/js/pages/SitePage.tsx
  static/js/types/modal_state.ts
  yarn.lock
Labels: Waiting on Author

#1081 fix spacing issue for single-line table cell content
  static/js/lib/ckeditor/plugins/TableMarkdownSyntax.test.tsx
  static/js/lib/ckeditor/plugins/TableMarkdownSyntax.ts
  static/js/lib/ckeditor/plugins/constants.ts
Labels: Needs Review

#1071 Option to add new content, support nested metadata for overwrite_ocw_course_content command
  ocw_import/api.py
  ocw_import/api_test.py
  ocw_import/management/commands/import_ocw_course_sites.py
  ocw_import/management/commands/overwrite_ocw_course_content.py
  ocw_import/tasks.py
  ocw_import/tasks_test.py
Labels: Needs Review

#1088 add code block support to CKEditor
  package.json
  static/js/lib/ckeditor/CKEditor.ts
  static/js/types/ckeditor.d.ts
  yarn.lock
Labels: Waiting on Author

#1089 [proposal] remove 'mobile' screen checkmark from PR template
  .github/pull_request_template.md
Labels: Needs Review

#1090 purge theme assets after deployment
  content_sync/pipelines/concourse.py
  content_sync/pipelines/concourse_test.py
  content_sync/pipelines/definitions/concourse/theme-assets-pipeline.yml
Labels: Waiting on Author

#1092 Improved site search for names, short_ids
  websites/views.py
  websites/views_test.py
Labels: Needs Review

#1107 Cc/metadata relative
  websites/management/commands/markdown_cleaning/baseurl_rule.py
  websites/management/commands/markdown_cleaning/baseurl_rule_test.py
  websites/management/commands/markdown_cleaning/cleaner.py
  websites/management/commands/markdown_cleaning/cleanup_rule.py
  websites/management/commands/markdown_cleaning/legacy_shortcodes_data_fix.py
  websites/management/commands/markdown_cleaning/legacy_shortcodes_data_fix_test.py
  websites/management/commands/markdown_cleaning/metadata_relative_urls.py
  websites/management/commands/markdown_cleaning/metadata_relative_urls_test.py
  websites/management/commands/markdown_cleaning/resource_file_rule.py
  websites/management/commands/markdown_cleaning/resource_file_rule_test.py
  websites/management/commands/markdown_cleaning/resource_link_delimiters.py
  websites/management/commands/markdown_cleaning/resource_link_delimiters_test.py
  websites/management/commands/markdown_cleaning/rootrelative_urls.py
  websites/management/commands/markdown_cleaning/rootrelative_urls_test.py
  websites/management/commands/markdown_cleaning/utils.py
  websites/management/commands/markdown_cleaning/utils_test.py
  websites/management/commands/markdown_cleaning/validate_urls.py
  websites/management/commands/markdown_cleanup.py
Labels: Waiting on Author

#1121 theme assets build cache busting take 3
  content_sync/pipelines/concourse.py
  content_sync/pipelines/concourse_test.py
  content_sync/pipelines/definitions/concourse/theme-assets-pipeline.yml
Labels: Waiting on Author

#1129 default metadata to empty object before iterating in seralizer
  websites/serializers.py
  websites/serializers_test.py
Labels: Needs Review

#1132 add inline code support to ckeditor
  static/js/lib/ckeditor/CKEditor.ts
  static/js/types/ckeditor.d.ts
Labels: Waiting on Author

#1127 Allow mass-publish to process a list of site names from a json file or comma-delimited string
  content_sync/management/commands/mass_publish.py
  ocw_import/management/commands/overwrite_ocw_course_content.py
Labels: Needs Review

#1101 add localdev support for collection gallery
  localdev/configs/ocw-www.yml
  static/js/resources/ocw-www.json
Labels: Waiting on Author, Blocked

#1120 Handle authentication for Concourse 7.7
  content_sync/pipelines/concourse.py
  content_sync/pipelines/concourse_test.py
  content_sync/tasks_test.py
  docker-compose.yml
Labels: Waiting on Author

#1134 Tweak internal site search so "HST.<number>" returns results
  websites/views.py
  websites/views_test.py
Labels: Waiting on Author

#1137 Remove extra parameter from < resource > shortcodes
  websites/management/commands/markdown_cleaning/baseurl_rule_test.py
  websites/management/commands/markdown_cleaning/cleaner.py
  websites/management/commands/markdown_cleaning/cleanup_rule.py
  websites/management/commands/markdown_cleaning/legacy_shortcodes_data_fix_test.py
  websites/management/commands/markdown_cleaning/metadata_relative_urls_test.py
  websites/management/commands/markdown_cleaning/parsing_utils.py
  websites/management/commands/markdown_cleaning/parsing_utils_test.py
  websites/management/commands/markdown_cleaning/remove_extra_resource_args.py
  websites/management/commands/markdown_cleaning/remove_extra_resource_args_test.py
  websites/management/commands/markdown_cleaning/resource_file_rule.py
  websites/management/commands/markdown_cleaning/resource_file_rule_test.py
  websites/management/commands/markdown_cleaning/resource_link_delimiters.py
  websites/management/commands/markdown_cleaning/resource_link_delimiters_test.py
  websites/management/commands/markdown_cleaning/rootrelative_urls_test.py
  websites/management/commands/markdown_cleaning/shortcode_grammar.py
  websites/management/commands/markdown_cleaning/shortcode_grammar_test.py
  websites/management/commands/markdown_cleaning/shortcode_logging_rule.py
  websites/management/commands/markdown_cleaning/shortcode_logging_rule_test.py
  websites/management/commands/markdown_cleanup.py
Labels: Waiting on Author

#1109 only query with published = true if cross_site is also true
  static/js/components/widgets/RelationField.test.tsx
  static/js/components/widgets/RelationField.tsx
Labels: Needs Review

#1146 a little typo in the localdev www config
  localdev/configs/ocw-www.yml
  static/js/resources/ocw-www.json
Labels: Needs Review

#1155 Fix gdrive import for ocw-www
  README.md
  app.json
  gdrive_sync/api.py
  localdev/configs/basic-site-config.yml
  main/settings.py
  static/js/resources/basic-site-config.json
  websites/site_config_api.py
  websites/site_config_api_test.py
Labels: Waiting on Author

#1147 changed italic delimiter to "*"
  static/js/lib/ckeditor/plugins/TableMarkdownSyntax.test.tsx
  static/js/lib/ckeditor/turndown.ts
  static/js/test_constants.ts
Labels: Waiting on Author

#1158 remove image inacessible
  websites/management/commands/markdown_cleaning/removal_rules.py
  websites/management/commands/markdown_cleanup.py
Labels: Waiting on Author

#1154 Cc/link parser and resolveuid
  websites/management/commands/markdown_cleaning/cleanup_rule.py
  websites/management/commands/markdown_cleaning/link_logging_rule.py
  websites/management/commands/markdown_cleaning/link_parser.py
  websites/management/commands/markdown_cleaning/link_parser_test.py
  websites/management/commands/markdown_cleaning/parsing_utils.py
  websites/management/commands/markdown_cleaning/parsing_utils_test.py
  websites/management/commands/markdown_cleaning/remove_extra_resource_args.py
  websites/management/commands/markdown_cleaning/resolveuid_rule.py
  websites/management/commands/markdown_cleaning/resolveuid_rule_test.py
  websites/management/commands/markdown_cleaning/rootrelative_urls.py
  websites/management/commands/markdown_cleaning/rootrelative_urls_test.py
  websites/management/commands/markdown_cleaning/shortcode_grammar.py
  websites/management/commands/markdown_cleaning/shortcode_grammar_test.py
  websites/management/commands/markdown_cleaning/shortcode_logging_rule.py
  websites/management/commands/markdown_cleaning/utils.py
  websites/management/commands/markdown_cleaning/utils_test.py
  websites/management/commands/markdown_cleanup.py
Labels: Needs Review

#1115 set parent_id when overwriting metadata.parent_uid
  ocw_import/api.py
  ocw_import/api_test.py
  ocw_import/management/commands/overwrite_ocw_course_content.py
Labels: Waiting on Author

#1170 Set a configurable limit to the number of redis pool connections
  app.json
  main/settings.py
  main/settings_test.py
Labels: Needs Review

#1165 Cc/rootrel with parentage
  websites/management/commands/markdown_cleaning/link_parser.py
  websites/management/commands/markdown_cleaning/parsing_utils.py
  websites/management/commands/markdown_cleaning/parsing_utils_test.py
  websites/management/commands/markdown_cleaning/rootrelative_urls.py
  websites/management/commands/markdown_cleaning/rootrelative_urls_test.py
  websites/management/commands/markdown_cleaning/testing_utils.py
  websites/management/commands/markdown_cleaning/utils.py
  websites/management/commands/markdown_cleaning/utils_test.py
  websites/management/commands/markdown_cleaning/validate_urls.py
  websites/management/commands/markdown_cleanup.py
Labels: Waiting on Author

#1181 Use get_redis_connection("redis").client() instead of app.backend.client
  content_sync/decorators.py
  content_sync/decorators_test.py
  main/settings.py
  requirements.in
  requirements.txt
Labels: Needs Review

#1174 Convert more baseurl links to resource_links
  websites/management/commands/markdown_cleaning/baseurl_rule.py
  websites/management/commands/markdown_cleaning/baseurl_rule_test.py
  websites/management/commands/markdown_cleaning/legacy_shortcodes_data_fix.py
  websites/management/commands/markdown_cleaning/legacy_shortcodes_data_fix_test.py
  websites/management/commands/markdown_cleaning/link_unescape.py
  websites/management/commands/markdown_cleaning/link_unescape_test.py
  websites/management/commands/markdown_cleaning/parsing_utils.py
  websites/management/commands/markdown_cleaning/parsing_utils_test.py
  websites/management/commands/markdown_cleaning/remove_extra_resource_args.py
  websites/management/commands/markdown_cleaning/remove_extra_resource_args_test.py
  websites/management/commands/markdown_cleaning/shortcode_grammar.py
  websites/management/commands/markdown_cleanup.py
Labels: Waiting on Author

#1178 handle links/images inside links correctly
  websites/management/commands/markdown_cleaning/link_parser.py
  websites/management/commands/markdown_cleaning/link_parser_test.py
  websites/management/commands/markdown_cleaning/rootrelative_urls.py
  websites/management/commands/markdown_cleaning/rootrelative_urls_test.py
  websites/management/commands/markdown_cleanup.py
Labels: Waiting on Author
