Repository mitodl/ocw-studio, pull requests merged in 2022-09, with the labels that each got.

#1459 Refactor Youtube token generation
  README.md
  requirements.in
  requirements.txt
  videos/management/commands/youtube_tokens.py
  videos/urls.py
  videos/views.py
  videos/views_test.py
Labels: Needs Review

#1467 mass build starter filter
  content_sync/api.py
  content_sync/management/commands/upsert_mass_build_pipeline.py
  content_sync/pipelines/concourse.py
  content_sync/pipelines/concourse_test.py
  content_sync/pipelines/definitions/concourse/mass-build-sites.yml
  websites/views.py
Labels: Waiting on Author

#1471 handle HTML files in static resources in mass-build-sites offline mode
  content_sync/pipelines/definitions/concourse/mass-build-sites.yml
Labels: Needs Review

#1475 Removed Underline formatting from toolbar
  static/js/lib/ckeditor/CKEditor.ts
Labels: Waiting on Author

#1466 Remove oauth2client
  requirements.in
  requirements.txt
  videos/conftest.py
  videos/youtube.py
  videos/youtube_test.py
Labels: Waiting on Author

#1468 feat: site dependencies shown while course unpublishing
  websites/constants.py
  websites/serializers.py
  websites/serializers_test.py
  websites/views.py
Labels: Waiting on Author

#1477 ZIP up offline sites in mass-build-sites
  content_sync/pipelines/definitions/concourse/mass-build-sites.yml
Labels: Waiting on Author

#1489 Fix WebsiteContent.full_metadata property
  websites/models.py
  websites/models_test.py
Labels: Waiting on Author

#1490 fix table bug ... emulate separate turndown instances
  static/js/lib/ckeditor/plugins/LegacyShortcodes.test.ts
  static/js/lib/ckeditor/plugins/Markdown.test.ts
  static/js/lib/ckeditor/plugins/Markdown.ts
  static/js/lib/ckeditor/plugins/ResourceEmbed.test.tsx
  static/js/lib/ckeditor/plugins/ResourceLinkMarkdownSyntax.test.ts
  static/js/lib/ckeditor/plugins/TableMarkdownSyntax.test.tsx
Labels: Needs Review

#1487 Adding functionality to search resources by filename
  websites/views.py
  websites/views_test.py
Labels: Waiting on Author

#1488 Log info when tables disappear
  .eslintrc.js
  jest.config.js
  package.json
  static/js/components/ErrorBoundary.tsx
  static/js/components/SiteContentEditor.test.tsx
  static/js/components/SiteContentEditor.tsx
  static/js/components/widgets/MarkdownEditor.tsx
  static/js/hooks/useAsyncError.ts
  static/js/index.tsx
  static/js/lib/ckeditor/plugins/Markdown.ts
  static/js/lib/ckeditor/plugins/validateMdConversion.test.ts
  static/js/lib/ckeditor/plugins/validateMdConversion.ts
  static/js/test_setup.ts
  static/js/testing_utils/IntegrationTestHelper.tsx
  static/js/testing_utils/index.ts
  yarn.lock
Labels: Needs Review

#1496 Bring back synced_checksum reset for nonpublished sites after a url change
  content_sync/factories.py
  websites/serializers.py
  websites/views_test.py
Labels: Waiting on Author

#1494 Provide a more helpful error log message when something goes wrong w/git authentication
  content_sync/apis/github.py
  content_sync/apis/github_test.py
Labels: Waiting on Author

#1503 Adding on_error and on_abort notifications to slack.
  content_sync/pipelines/definitions/concourse/site-pipeline.yml
Labels: Waiting on Author, DevOps

#1505 fix mass-build-sites offline HTML file detection
  content_sync/pipelines/definitions/concourse/mass-build-sites.yml
Labels: Needs Review

#1507 proper pathing for the zip command
  content_sync/pipelines/definitions/concourse/mass-build-sites.yml
Labels: Waiting on Author
