Repository mitodl/ocw-studio, pull requests merged in 2023-06, with the labels that each got.

#1827 fix: too many upload success emails
  videos/tasks.py
  videos/tasks_test.py
Labels: Waiting on Author

#1828 fix @types/react versions
  package.json
  yarn.lock
Labels: Waiting on Author

#1830 update typescript to 4.9.5
  package.json
  static/js/lib/ckeditor/plugins/util.ts
  yarn.lock
Labels: Waiting on Author

#1831 Update linting, formatting
  package.json
  static/js/components/Dialog.test.tsx
  static/js/components/DriveSyncStatusIndicator.test.tsx
  static/js/components/PublishDrawer.test.tsx
  static/js/components/PublishDrawer.tsx
  static/js/components/RepeatableContentListing.tsx
  static/js/components/SingletonsContentListing.test.tsx
  static/js/components/SiteCollaboratorList.test.tsx
  static/js/components/SiteCollaboratorList.tsx
  static/js/components/SiteContentEditor.tsx
  static/js/components/SiteContentEditorDrawer.test.tsx
  static/js/components/SiteContentListing.tsx
  static/js/components/SortableItem.test.tsx
  static/js/components/SortableItem.tsx
  static/js/components/forms/MenuItemForm.tsx
  static/js/components/forms/SiteCollaboratorForm.test.tsx
  static/js/components/forms/SiteCollaboratorForm.tsx
  static/js/components/forms/SiteForm.tsx
  static/js/components/forms/validation.ts
  static/js/components/util/Router.tsx
  static/js/components/widgets/FileUploadField.test.tsx
  static/js/components/widgets/HierarchicalSelectField.test.tsx
  static/js/components/widgets/HierarchicalSelectField.tsx
  static/js/components/widgets/MarkdownEditor.test.tsx
  static/js/components/widgets/MarkdownEditor.tsx
  static/js/components/widgets/MenuField.tsx
  static/js/components/widgets/RelationField.test.tsx
  static/js/components/widgets/RelationField.tsx
  static/js/components/widgets/ResourcePickerDialog.test.tsx
  static/js/components/widgets/ResourcePickerListing.test.tsx
  static/js/components/widgets/SelectField.tsx
  static/js/constants.ts
  static/js/hooks/websites.test.ts
  static/js/lib/ckeditor/plugins/LegacyShortcodes.ts
  static/js/lib/ckeditor/plugins/Markdown.test.ts
  static/js/lib/ckeditor/plugins/Markdown.ts
  static/js/lib/ckeditor/plugins/ResourceEmbed.ts
  static/js/lib/ckeditor/plugins/ResourceLink.ts
  static/js/lib/ckeditor/plugins/ResourceLinkUI.ts
  static/js/lib/ckeditor/plugins/TableMarkdownSyntax.test.tsx
  static/js/lib/ckeditor/plugins/constants.ts
  static/js/lib/ckeditor/plugins/test_util.ts
  static/js/lib/ckeditor/plugins/util.test.ts
  static/js/lib/urls.ts
  static/js/lib/util.ts
  static/js/pages/SiteCreationPage.tsx
  static/js/pages/SitesDashboard.tsx
  static/js/query-configs/websites.ts
  static/js/selectors/websites.ts
  static/js/store/user/index.ts
  static/js/util/index.ts
  static/js/util/integration_test_helper_old.tsx
  yarn.lock
Labels: Waiting on Author

#1836 ZIPs with and without videos
  content_sync/pipelines/concourse_test.py
  content_sync/pipelines/definitions/concourse/site-pipeline.yml
Labels: Waiting on Author, Blocker, product:ocw

#1842 update swc
  package.json
  static/js/components/SingletonsContentListing.test.tsx
  static/js/components/SiteContentEditor.test.tsx
  static/js/components/forms/validation.test.ts
  static/js/lib/ckeditor/plugins/Markdown.ts
  static/js/pages/SitesDashboard.test.tsx
  static/js/testing_utils/IntegrationTestHelper.tsx
  static/js/types/ckeditor.d.ts
  static/js/util/integration_test_helper_old.tsx
  yarn.lock
Labels: Waiting on Author

#1826 enhancement: upgrade publisher
  content_sync/api_test.py
  content_sync/pipelines/concourse.py
  content_sync/pipelines/concourse_test.py
  content_sync/pipelines/definitions/concourse/mass-build-sites.yml
  content_sync/pipelines/definitions/concourse/site-pipeline.yml
  content_sync/pipelines/definitions/concourse/theme-assets-pipeline.yml
  content_sync/tasks_test.py
  content_sync/test_constants.py
  content_sync/utils.py
Labels: Needs Review

#1843 chore: upgrade actions' versions
  .github/workflows/ci.yml
  .github/workflows/production.yml
  .github/workflows/release-candiate.yml
Labels: Waiting on Author

#1851 GDrive File Size Sync
  gdrive_sync/admin.py
  gdrive_sync/api.py
  gdrive_sync/api_test.py
  gdrive_sync/constants.py
  gdrive_sync/factories.py
  gdrive_sync/migrations/0008_drivefile_size.py
  gdrive_sync/models.py
  localdev/configs/basic-site-config.yml
  static/js/resources/basic-site-config.json
  videos/tasks_test.py
Labels: Waiting on Author

#1849 fix a useless test
  static/js/components/AuthenticationAlert.test.tsx
  static/js/test_util.ts
Labels: Waiting on Author
