Repository mitodl/ocw-studio, pull requests merged in 2023-05, with the labels that each got.

#1763 separate online and offline parts of site-pipeline into separate jobs
  content_sync/pipelines/concourse_test.py
  content_sync/pipelines/definitions/concourse/site-pipeline.yml
Labels: Waiting on Author

#1777 fix static-resources-subdirectory pathing
  content_sync/pipelines/concourse.py
  content_sync/pipelines/concourse_test.py
  content_sync/pipelines/definitions/concourse/site-pipeline.yml
Labels: Waiting on Author

#1780 move webpack-json resource back to forked s3 resource type
  content_sync/pipelines/definitions/concourse/site-pipeline.yml
Labels: Waiting on Author

#1774 config: Add renovate config for ocw-studio
  renovate.json
Labels: Needs Review, DevOps

#1792 Incorrect files path for Sync missing captions
  videos/utils.py
Labels: Needs Review

#1795 Revert "Incorrect files path for Sync missing captions"
  videos/utils.py
Labels: Waiting on Author

#1759 fix: should not delete resources that are being used in a site
  gdrive_sync/api.py
  gdrive_sync/api_test.py
  gdrive_sync/conftest.py
  gdrive_sync/models.py
  gdrive_sync/models_test.py
  websites/models.py
  websites/site_config_api.py
  websites/utils.py
Labels: Waiting on Author

#1809 Sync missing captions - Fixed incorrect file paths
  videos/management/commands/sync_missing_captions.py
  videos/utils.py
Labels: Needs Review

#1817 template noindex variable into mass-build-sites pipeline
  content_sync/pipelines/concourse.py
  content_sync/pipelines/concourse_test.py
Labels: Waiting on Author, product:ocw

#1811 SENTRY_ENV added to the themes-pipelines
  app.json
  content_sync/pipelines/concourse.py
  content_sync/pipelines/definitions/concourse/theme-assets-pipeline.yml
  main/settings.py
Labels: Waiting on Author

#1823 Fix a linting issue for renovate PR
  static/js/types/modal_state.ts
Labels: Waiting on Author
