Repository mitodl/ocw-studio, pull requests merged in 2023-11, with the labels that each got.

#2017 update FilterWebpackArtifactsStep to support webpack-manifest-plugin
  content_sync/pipelines/definitions/concourse/site_pipeline.py
  content_sync/pipelines/definitions/concourse/site_pipeline_test.py
Labels: Needs Review

#2023 compose file updates
  docker-compose-arm64.yml
  docker-compose.yml
Labels: Waiting on Author, product:ocw

#2020 ci: add pull_request trigger
  .github/workflows/ci.yml
Labels: Needs Review

#2026 test: improve tests for existing captions
  fixtures/common.py
  gdrive_sync/api_test.py
  main/utils_test.py
  videos/models_test.py
  videos/tasks_test.py
  videos/utils_test.py
  websites/factories.py
Labels: Waiting on Author
