Repository mitodl/ocw-studio, pull requests merged in 2023-07, with the labels that each got.

#1865 don't generate or sync zips for the root website
  content_sync/pipelines/concourse.py
  content_sync/pipelines/definitions/concourse/site-pipeline.yml
Labels: Waiting on Author, product:ocw

#1875 make drivefile size a BigInteger
  gdrive_sync/migrations/0009_use_bigint_for_drivefile_size.py
  gdrive_sync/models.py
  gdrive_sync/models_test.py
Labels: Needs Review

#1861 chore: create populate_file_sizes command
  gdrive_sync/conftest.py
  gdrive_sync/management/commands/populate_file_sizes.py
  gdrive_sync/tasks.py
  gdrive_sync/tasks_test.py
  gdrive_sync/utils.py
  gdrive_sync/utils_test.py
Labels: Waiting on Author

#1879 fix: strip '/' from keys in populate_file_sizes
  gdrive_sync/utils.py
Labels: Waiting on Author

#1891 Bump pyyaml to 6.0.1 and yamale to 4.0.4
  requirements.in
  requirements.txt
Labels: Needs Review

#1894 add ol-concourse common components
  content_sync/pipelines/definitions/__init__.py
  content_sync/pipelines/definitions/concourse/__init__.py
  content_sync/pipelines/definitions/concourse/common/__init__.py
  content_sync/pipelines/definitions/concourse/common/identifiers.py
  content_sync/pipelines/definitions/concourse/common/image_resources.py
  content_sync/pipelines/definitions/concourse/common/resource_types.py
  content_sync/pipelines/definitions/concourse/common/resources.py
  content_sync/pipelines/definitions/concourse/common/steps.py
  content_sync/pipelines/definitions/concourse/common/steps_test.py
  requirements.in
  requirements.txt
Labels: Needs Review, product:ocw

#1893 Use Poetry for managing Python Dependencies
  .github/workflows/ci.yml
  Dockerfile
  app.json
  poetry.lock
  pyproject.toml
  runtime.txt
  test_requirements.txt
  travis/python_tests.sh
Labels: Needs Review

#1898 Configure uWSGI stats server
  poetry.lock
  pyproject.toml
  uwsgi.ini
Labels: Waiting on Author

#1896 overhaul theme assets pipeline definition
  content_sync/pipelines/definitions/concourse/theme_assets_pipeline.py
  content_sync/pipelines/definitions/concourse/theme_assets_pipeline_test.py
Labels: Needs Review

#1873 Fix "publish to draft" causing sites to be hidden in mirror drive
  websites/api.py
  websites/api_test.py
Labels: Waiting on Author

#1886 Tune uWSGI settings
  uwsgi.ini
Labels: Waiting on Author, product:ocw
