Repository mitodl/ocw-studio, pull requests merged in 2025-01, with the labels that each got.

#2326 Update Documentation for External Resources Model with Wayback Machine and API Changes
  external_resources/README.md
Labels: Waiting on Author

#2373 Remove "name" field from the metadata of stories in WebsiteContent
  websites/migrations/0059_remove_name_from_stories_websitecontent_metadata.py
Labels: Needs Review

#2370 Add Video Resource Functionality
  static/js/components/RepeatableContentListing.test.tsx
  static/js/components/RepeatableContentListing.tsx
  static/js/components/forms/SiteContentForm.tsx
Labels: Needs Review

#2379 Introduce Environment Variable to Control Wayback Machine Tasks
  .env.example
  app.json
  external_resources/README.md
  external_resources/constants.py
  external_resources/management/commands/submit_sites_to_wayback.py
  external_resources/management/commands/update_wayback_status.py
  external_resources/tasks.py
  external_resources/tasks_test.py
  main/settings.py
Labels: Needs Review

#2382 Remove submitting to wayback machine logging when task is not executed
  external_resources/signals.py
Labels: Needs Review

#2378 added management command to detect unrelated files in a website
  websites/management/commands/detect_unrelated_content.py
Labels: Needs Review, Waiting on Author

#2384 Added deletable content type list in environment
  README.md
  app.json
  main/settings.py
  main/views.py
  main/views_test.py
  static/js/components/RepeatableContentListing.test.tsx
  static/js/components/RepeatableContentListing.tsx
  static/js/types/globals.d.ts
Labels: Waiting on Author
