Repository mitodl/ocw-studio, pull requests merged in 2025-07, with the labels that each got.

#2607 fix: use iterator instead of loadig all records in memory
  websites/migrations/0060_add_referencing_content_for_existing_resources.py
Labels: Waiting on Author

#2626 make Github API timeout configurable
  app.json
  content_sync/apis/github.py
  main/settings.py
Labels: Waiting on Author

#2602 Ability to delete video resources
  static/js/components/RepeatableContentListing.tsx
  static/js/types/websites.ts
  static/js/util/factories/websites.ts
  websites/deletion_utils.py
  websites/deletion_utils_test.py
  websites/serializers.py
  websites/serializers_test.py
  websites/views.py
  websites/views_test.py
Labels: Waiting on Author

#2635 Remove Course Introduction learning resource type
  localdev/configs/ocw-course-site-config.yml
  static/js/resources/ocw-course-site-config.json
Labels: Waiting on Author

#2646 Skip recursion by using skip_sync flag variable for Add Video Resource
  videos/signals.py
  videos/tasks.py
Labels: Needs Review

#2651 fix: added check for root site when checking hide_download setting
  websites/views.py
Labels: Needs Review, Waiting on Author
